<script lang="ts">
    import type {
        SHURecord,
        SHUReport,
        SHUGenerateRequest,
        SHUSaveRequest,
        SHUAutoGenerateRequest,
        SHUAutoReport,
        SHUAutoSaveRequest,
        SHUAnggotaSaveRequest,
        SHUAnggotaRecord,
        SHUAnggotaSaveResponse,
        SHUAnggotaHistoryResponse,
    } from "$lib/types";
    import { invalidateAll } from "$app/navigation";
    import axios from "$lib/api";
    import { onMount } from "svelte";

    export let data;

    let shuRecords: SHURecord[] = data.shuRecords || [];
    let userShuHistory: any[] = data.userShuHistory || [];
    const currentUser = data.currentUser;
    const canManageSHU = data.canManageSHU || false;

    // Reactive updates when data changes
    $: {
        shuRecords = data.shuRecords || [];
        userShuHistory = data.userShuHistory || [];
        console.log(
            "🔄 Reactive update - userShuHistory:",
            userShuHistory.length,
        );

        // Debug first user SHU record when available
        if (userShuHistory.length > 0) {
            console.log("🔍 First user SHU record:", userShuHistory[0]);
            console.log("🔍 Available fields:", Object.keys(userShuHistory[0]));
        }
    }

    // Debug logging
    console.log("🚀 SHU page loaded");
    console.log(
        "👤 Current user:",
        currentUser?.email,
        currentUser?.role?.name,
    );
    console.log("🔐 Can manage SHU:", canManageSHU);
    console.log("📊 SHU records count:", shuRecords.length);
    console.log("📈 User SHU history count:", userShuHistory.length);

    // Debug SHU records structure
    if (shuRecords.length > 0) {
        console.log("🔍 Sample SHU record structure:", shuRecords[0]);
        console.log("🔍 SHU record fields:", Object.keys(shuRecords[0]));
        console.log("🔍 SHU record ID field:", shuRecords[0].id);
    }

    // Debug user SHU history structure
    if (userShuHistory.length > 0) {
        console.log("🔍 Sample user SHU history:", userShuHistory[0]);
        console.log(
            "🔍 User SHU history fields:",
            Object.keys(userShuHistory[0]),
        );
    } else {
        console.log(
            "📝 User SHU history is empty, checking if data was fetched",
        );
        console.log("📝 Raw userShuHistory value:", data.userShuHistory);
        console.log("📝 Type of userShuHistory:", typeof data.userShuHistory);
    }

    // Manual refresh function for debugging
    async function refreshUserData() {
        console.log("🔄 Manual refresh triggered");
        try {
            await invalidateAll();
            // Update reactive variables
            userShuHistory = data.userShuHistory || [];
            console.log(
                "✅ Refresh completed, new userShuHistory:",
                userShuHistory,
            );
        } catch (error) {
            console.error("❌ Refresh failed:", error);
        }
    }

    // Modal states
    let showGenerateModal = false;
    let showAutoGenerateModal = false;
    let showDetailModal = false;
    let showUserGenerateModal = false;
    let selectedSHU: SHURecord | null = null;
    let generatedReport: SHUReport | null = null;
    let autoGeneratedReport: SHUAutoReport | null = null;

    // Form data
    let generateForm: SHUGenerateRequest = {
        tahun: new Date().getFullYear(),
        total_shu_koperasi: 0,
    };

    // Variables for automated SHU generation - only expenses needed
    let autoGenerateForm: SHUAutoGenerateRequest = {
        tahun: new Date().getFullYear(),
        beban_operasional: 0,
        beban_non_operasional: 0,
        beban_pajak: 0,
    };

    let saveForm: SHUSaveRequest = {
        tahun: new Date().getFullYear(),
        total_shu: 0,
        status: "draft",
    };

    // User SHU save variables
    let userSaveTahun: number = new Date().getFullYear();
    let showUserSaveModal = false;
    let savingUserSHU = false;

    // Utility functions
    function formatCurrency(amount: number): string {
        return new Intl.NumberFormat("id-ID", {
            style: "currency",
            currency: "IDR",
            minimumFractionDigits: 0,
        }).format(amount);
    }

    function formatDate(dateString: string): string {
        return new Date(dateString).toLocaleDateString("id-ID", {
            year: "numeric",
            month: "long",
            day: "numeric",
        });
    }

    function showSuccessNotification(message: string) {
        alert(message); // TODO: Replace with proper toast notification
    }

    // Modal functions
    function openGenerateModal() {
        generateForm = {
            tahun: new Date().getFullYear(),
            total_shu_koperasi: 0,
        };
        generatedReport = null;
        showGenerateModal = true;
    }

    function openAutoGenerateModal() {
        autoGenerateForm = {
            tahun: new Date().getFullYear(),
            beban_operasional: 0,
            beban_non_operasional: 0,
            beban_pajak: 0,
        };
        autoGeneratedReport = null;
        showAutoGenerateModal = true;
    }

    function openUserGenerateModal() {
        showUserGenerateModal = true;
    }

    function openDetailModal(shu: SHURecord) {
        selectedSHU = shu;
        showDetailModal = true;
    }

    function closeModals() {
        showGenerateModal = false;
        showAutoGenerateModal = false;
        showDetailModal = false;
        showUserGenerateModal = false;
        showUserSaveModal = false;
        selectedSHU = null;
        generatedReport = null;
        autoGeneratedReport = null;
    }

    // SHU operations
    async function generateSHUReport() {
        try {
            console.log("📝 Generating SHU report:", generateForm);
            const response = await axios.post("/shu/generate", generateForm);

            generatedReport = response.data.data;
            console.log("✅ SHU report generated:", generatedReport);

            showSuccessNotification("Laporan SHU berhasil digenerate!");
        } catch (error: any) {
            console.error("❌ Error generating SHU report:", error);
            alert(
                `Gagal generate laporan SHU: ${error.response?.data?.message || error.message}`,
            );
        }
    }

    async function generateAutoSHUReport() {
        try {
            console.log(
                "🤖 Generating automated SHU report:",
                autoGenerateForm,
            );
            const response = await axios.post(
                "/shu/generate-auto",
                autoGenerateForm,
            );

            autoGeneratedReport = response.data.data;
            console.log(
                "✅ Automated SHU report generated:",
                autoGeneratedReport,
            );

            showSuccessNotification(
                "Laporan SHU otomatis berhasil digenerate!",
            );
        } catch (error: any) {
            console.error("❌ Error generating automated SHU report:", error);
            alert(
                `Gagal generate laporan SHU otomatis: ${error.response?.data?.message || error.message}`,
            );
        }
    }

    async function saveAutoSHUReport() {
        console.log("🚀 Starting saveAutoSHUReport function");

        if (!autoGeneratedReport) {
            console.log("❌ No autoGeneratedReport found");
            alert("Silakan generate laporan otomatis terlebih dahulu");
            return;
        }

        try {
            // Debug the values first
            console.log(
                "🔍 Debug - autoGeneratedReport:",
                JSON.stringify(autoGeneratedReport, null, 2),
            );

            // Convert values with extra validation
            const totalSHU = Math.round(
                Number(autoGeneratedReport.total_shu_koperasi) || 0,
            );
            const tahun =
                Number(autoGeneratedReport.tahun) || new Date().getFullYear();
            const pendapatanOp = Math.round(
                Number(autoGeneratedReport.pendapatan_operasional) || 0,
            );
            const pendapatanNonOp = Math.round(
                Number(autoGeneratedReport.pendapatan_non_operasional) || 0,
            );
            const bebanOp = Math.round(
                Number(autoGeneratedReport.beban_operasional) || 0,
            );
            const bebanNonOp = Math.round(
                Number(autoGeneratedReport.beban_non_operasional) || 0,
            );
            const bebanPajak = Math.round(
                Number(autoGeneratedReport.beban_pajak) || 0,
            );

            console.log("🔍 Raw values from autoGeneratedReport:");
            console.log(
                "  - total_shu_koperasi:",
                autoGeneratedReport.total_shu_koperasi,
                typeof autoGeneratedReport.total_shu_koperasi,
            );
            console.log(
                "  - tahun:",
                autoGeneratedReport.tahun,
                typeof autoGeneratedReport.tahun,
            );

            console.log("🔍 Converted values:");
            console.log("  - totalSHU:", totalSHU, typeof totalSHU);
            console.log("  - tahun:", tahun, typeof tahun);

            // Check if SHU Total is valid for saving
            if (totalSHU <= 0) {
                alert(
                    `Tidak dapat menyimpan laporan SHU karena total SHU adalah ${formatCurrency(totalSHU)}.\n\nPastikan pendapatan lebih besar dari total beban untuk menghasilkan SHU positif.`,
                );
                return;
            }

            // Use the EXACT structure from API documentation
            const saveData = {
                tahun: tahun,
                pendapatan_operasional: pendapatanOp,
                pendapatan_non_operasional: pendapatanNonOp,
                beban_operasional: bebanOp,
                beban_non_operasional: bebanNonOp,
                beban_pajak: bebanPajak,
                total_shu: totalSHU, // This is the correct field name from API docs
                status: "draft",
            };

            // Final validation check
            console.log("🔍 Final payload validation:");
            console.log(
                "  - tahun exists:",
                saveData.tahun !== undefined && saveData.tahun !== null,
            );
            console.log(
                "  - tahun value:",
                saveData.tahun,
                typeof saveData.tahun,
            );
            console.log(
                "  - total_shu exists:",
                saveData.total_shu !== undefined && saveData.total_shu !== null,
            );
            console.log(
                "  - total_shu value:",
                saveData.total_shu,
                typeof saveData.total_shu,
            );

            console.log(
                "💾 Final payload (matching API docs):",
                JSON.stringify(saveData, null, 2),
            );

            const response = await axios.post("/shu/save-auto", saveData);
            console.log("✅ Save successful:", response.data);

            // Refresh data
            await invalidateAll();
            closeModals();
            showSuccessNotification(
                "Laporan SHU otomatis berhasil disimpan ke daftar!",
            );
        } catch (error: any) {
            console.error("❌ All save attempts failed:", error);
            console.error("❌ Final error response:", error.response?.data);
            console.error("❌ Error status:", error.response?.status);

            const errorMessage =
                error.response?.data?.message ||
                error.response?.data?.error ||
                error.message ||
                "Unknown error occurred";

            alert(`Gagal menyimpan laporan SHU otomatis: ${errorMessage}`);
        }
    }

    async function generateUserSHU() {
        try {
            console.log("👤 Generating user SHU for user ID:", currentUser.id);

            // User SHU generation now requires year input according to API docs
            const currentYear = new Date().getFullYear();
            const requestData = {
                Tahun: currentYear,
                TotalSHUKoperasi: 0, // Try with the fields the error mentioned
            };

            console.log(
                "� API endpoint:",
                `/shu/user/${currentUser.id}/generate`,
            );
            console.log("📤 Request data:", requestData);

            const response = await axios.post(
                `/shu/user/${currentUser.id}/generate`,
                requestData,
            );

            console.log("✅ User SHU generated:", response.data);

            // Refresh user history
            await invalidateAll();
            closeModals();
            showSuccessNotification("SHU pribadi berhasil digenerate!");
        } catch (error: any) {
            console.error("❌ Error generating user SHU:", error);
            console.error("❌ Error response:", error.response?.data);
            console.error("❌ Error status:", error.response?.status);

            // Handle specific error cases
            if (error.response?.status === 403) {
                alert(
                    "Access Denied: Anda tidak memiliki izin untuk generate SHU pribadi.\n\nKemungkinan penyebab:\n• Fitur belum aktif untuk user biasa\n• Perlu izin khusus dari admin\n• Role/permission tidak sesuai",
                );
                return;
            }

            if (error.response?.status === 401) {
                alert(
                    "Authentication Error: Sesi login Anda mungkin telah berakhir.\n\nSilakan refresh halaman dan login kembali.",
                );
                return;
            }

            // Try with 'tahun' field if current format fails
            if (error.response?.status === 400) {
                try {
                    console.log("🔄 Retrying with alternative format...");
                    const alternativeData = { tahun: new Date().getFullYear() };
                    console.log(
                        "📤 Alternative request data:",
                        alternativeData,
                    );

                    const retryResponse = await axios.post(
                        `/shu/user/${currentUser.id}/generate`,
                        alternativeData,
                    );
                    console.log(
                        "✅ User SHU generated with alternative format:",
                        retryResponse.data,
                    );

                    await invalidateAll();
                    closeModals();
                    showSuccessNotification("SHU pribadi berhasil digenerate!");
                    return;
                } catch (retryError: any) {
                    console.error(
                        "❌ Alternative format also failed:",
                        retryError,
                    );
                }
            }

            const errorMessage =
                error.response?.data?.message ||
                error.response?.data?.error ||
                error.message ||
                "API endpoint may not be implemented";

            alert(
                `Gagal generate SHU pribadi: ${errorMessage}\n\nEndpoint: /shu/user/${currentUser.id}/generate\nStatus: ${error.response?.status || "Unknown"}`,
            );
        }
    }

    async function saveUserSHU(tahun: number) {
        try {
            // Validation
            if (!tahun || tahun < 2020 || tahun > 2030) {
                alert(
                    "Tahun tidak valid. Silakan masukkan tahun antara 2020-2030",
                );
                return;
            }

            if (!currentUser?.id) {
                alert("Error: User ID tidak ditemukan. Silakan login ulang.");
                return;
            }

            console.log(
                "💾 Saving user SHU for year:",
                tahun,
                "user ID:",
                currentUser.id,
            );

            const saveRequest: SHUAnggotaSaveRequest = {
                tahun: tahun,
            };

            console.log("📤 Save request data:", saveRequest);

            const response = await axios.post<SHUAnggotaSaveResponse>(
                `/shu-anggota/user/${currentUser.id}/save`,
                saveRequest,
            );

            console.log("✅ User SHU saved successfully:", response.data);

            // Refresh user history to show the newly saved record
            await invalidateAll();

            showSuccessNotification(
                `SHU untuk tahun ${tahun} berhasil disimpan!`,
            );

            return response.data.data;
        } catch (error: any) {
            console.error("❌ Error saving user SHU:", error);
            console.error("❌ Error response:", error.response?.data);
            console.error("❌ Error status:", error.response?.status);

            // Handle specific error cases
            if (error.response?.status === 403) {
                alert(
                    "Access Denied: Anda tidak memiliki izin untuk menyimpan SHU pribadi.\n\nKemungkinan penyebab:\n• Fitur belum aktif\n• Role/permission tidak sesuai",
                );
                return;
            }

            if (error.response?.status === 401) {
                alert(
                    "Authentication Error: Sesi login Anda mungkin telah berakhir.\n\nSilakan refresh halaman dan login kembali.",
                );
                return;
            }

            if (error.response?.status === 400) {
                const errorMessage =
                    error.response?.data?.message ||
                    error.response?.data?.error ||
                    "Data request tidak valid";
                alert(
                    `Gagal menyimpan SHU: ${errorMessage}\n\nPastikan:\n• Tahun yang dipilih valid\n• Anda memiliki data transaksi di tahun tersebut`,
                );
                return;
            }

            if (error.response?.status === 404) {
                alert(
                    `SHU untuk tahun ${tahun} tidak ditemukan.\n\nKemungkinan penyebab:\n• Data SHU tahun ${tahun} belum dibuat oleh admin\n• Tidak ada transaksi di tahun tersebut`,
                );
                return;
            }

            const errorMessage =
                error.response?.data?.message ||
                error.response?.data?.error ||
                error.message ||
                "Unknown error occurred";

            alert(
                `Gagal menyimpan SHU pribadi: ${errorMessage}\n\nEndpoint: /shu-anggota/user/${currentUser.id}/save\nStatus: ${error.response?.status || "Unknown"}`,
            );
        }
    }

    async function saveSHUReport() {
        if (!generatedReport) {
            alert("Silakan generate laporan terlebih dahulu");
            return;
        }

        try {
            saveForm.tahun = generatedReport.tahun;
            saveForm.total_shu = generatedReport.total_shu_koperasi;

            console.log("💾 Saving SHU record:", saveForm);
            await axios.post("/shu", saveForm);

            // Refresh data
            await invalidateAll();

            closeModals();
            showSuccessNotification("Laporan SHU berhasil disimpan!");
        } catch (error: any) {
            console.error("❌ Error saving SHU record:", error);
            alert(
                `Gagal menyimpan laporan SHU: ${error.response?.data?.message || error.message}`,
            );
        }
    }

    async function deleteSHURecord(id: number) {
        console.log("🔍 Delete function called with ID:", id, typeof id);

        if (!id || id === undefined) {
            console.error("❌ Invalid ID for deletion:", id);
            alert("Error: ID SHU tidak valid untuk penghapusan");
            return;
        }

        if (!confirm("Apakah Anda yakin ingin menghapus laporan SHU ini?")) {
            return;
        }

        try {
            console.log("🗑️ Deleting SHU record with ID:", id);
            await axios.delete(`/shu/${id}`);

            // Refresh data
            await invalidateAll();

            showSuccessNotification("Laporan SHU berhasil dihapus!");
        } catch (error: any) {
            console.error("❌ Error deleting SHU record:", error);
            console.error("❌ Delete endpoint called:", `/shu/${id}`);
            alert(
                `Gagal menghapus laporan SHU: ${error.response?.data?.message || error.message}`,
            );
        }
    }

    // Alternative delete function using year when ID is not available
    async function deleteSHURecordByYear(tahun: number) {
        try {
            console.log("🗑️ Attempting to delete SHU record by year:", tahun);

            // Try different possible endpoints
            const possibleEndpoints = [
                `/shu/year/${tahun}`,
                `/shu/tahun/${tahun}`,
                `/shu?tahun=${tahun}`,
            ];

            let success = false;
            for (const endpoint of possibleEndpoints) {
                try {
                    console.log("🔄 Trying endpoint:", endpoint);
                    await axios.delete(endpoint);
                    success = true;
                    break;
                } catch (error: any) {
                    console.log(
                        `❌ Endpoint ${endpoint} failed:`,
                        error.response?.status,
                    );
                }
            }

            if (success) {
                await invalidateAll();
                showSuccessNotification("Laporan SHU berhasil dihapus!");
            } else {
                throw new Error("Tidak ada endpoint delete yang berhasil");
            }
        } catch (error: any) {
            console.error("❌ Error deleting SHU record by year:", error);
            alert(
                `Gagal menghapus laporan SHU: ${error.response?.data?.message || error.message}\n\nMungkin fitur hapus belum tersedia atau perlu ID yang valid.`,
            );
        }
    }

    async function generatePDF(shu: SHURecord) {
        try {
            console.log("📄 Generating PDF for SHU:", shu.id);

            // Create HTML content for PDF
            const htmlContent = `
                <!DOCTYPE html>
                <html>
                <head>
                    <meta charset="utf-8">
                    <title>Laporan SHU ${shu.tahun}</title>
                    <style>
                        body { font-family: Arial, sans-serif; margin: 20px; }
                        .header { text-align: center; margin-bottom: 30px; }
                        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }
                        .info-item { margin-bottom: 10px; }
                        .label { font-weight: bold; color: #666; }
                        .value { font-size: 18px; font-weight: bold; }
                        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                        th, td { padding: 8px; text-align: left; border-bottom: 1px solid #ddd; }
                        th { background-color: #f2f2f2; font-weight: bold; }
                        .currency { text-align: right; }
                        .total-row { font-weight: bold; background-color: #f8f9fa; }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <h1>LAPORAN SISA HASIL USAHA (SHU)</h1>
                        <h2>TAHUN ${shu.tahun}</h2>
                        <p>Tanggal: ${formatDate(shu.created_at)}</p>
                    </div>
                    
                    <div class="info-grid">
                        <div class="info-item">
                            <div class="label">Total SHU Koperasi:</div>
                            <div class="value">${formatCurrency(shu.total_shu)}</div>
                        </div>
                        <div class="info-item">
                            <div class="label">Status:</div>
                            <div class="value">${shu.status === "final" ? "Final" : "Draft"}</div>
                        </div>
                    </div>
                    
                    ${
                        shu.shu_report
                            ? `
                    <h3>Detail Perhitungan</h3>
                    <div class="info-grid">
                        <div class="info-item">
                            <div class="label">Persentase Jasa Modal:</div>
                            <div class="value">${shu.shu_report.persen_jasa_modal}%</div>
                        </div>
                        <div class="info-item">
                            <div class="label">Persentase Jasa Usaha:</div>
                            <div class="value">${shu.shu_report.persen_jasa_usaha}%</div>
                        </div>
                        <div class="info-item">
                            <div class="label">Total Simpanan Semua Anggota:</div>
                            <div class="value">${formatCurrency(shu.shu_report.total_simpanan_all)}</div>
                        </div>
                        <div class="info-item">
                            <div class="label">Total Penjualan Semua Anggota:</div>
                            <div class="value">${formatCurrency(shu.shu_report.total_penjualan_all)}</div>
                        </div>
                    </div>
                    
                    <h3>Detail Pembagian SHU Anggota</h3>
                    <table>
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Email Anggota</th>
                                <th>Total Simpanan</th>
                                <th>Total Penjualan</th>
                                <th>Jasa Modal</th>
                                <th>Jasa Usaha</th>
                                <th>Total SHU</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${shu.shu_report.detail_anggota
                                .map(
                                    (member, index) => `
                                <tr>
                                    <td>${index + 1}</td>
                                    <td>${member.email}</td>
                                    <td class="currency">${formatCurrency(member.total_simpanan)}</td>
                                    <td class="currency">${formatCurrency(member.total_penjualan)}</td>
                                    <td class="currency">${formatCurrency(member.jasa_modal)}</td>
                                    <td class="currency">${formatCurrency(member.jasa_usaha)}</td>
                                    <td class="currency">${formatCurrency(member.total_shu_anggota)}</td>
                                </tr>
                            `,
                                )
                                .join("")}
                            <tr class="total-row">
                                <td colspan="6">TOTAL</td>
                                <td class="currency">${formatCurrency(shu.shu_report.detail_anggota.reduce((sum, member) => sum + member.total_shu_anggota, 0))}</td>
                            </tr>
                        </tbody>
                    </table>
                    `
                            : ""
                    }
                    
                    <div style="margin-top: 50px; text-align: center; color: #666;">
                        <p>Laporan ini digenerate secara otomatis oleh sistem Koperasi</p>
                        <p>Tanggal generate: ${new Date().toLocaleString("id-ID")}</p>
                    </div>
                </body>
                </html>
            `;

            // Create and download HTML file (can be opened in browser and printed to PDF)
            const blob = new Blob([htmlContent], { type: "text/html" });
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `SHU_Report_${shu.tahun}.html`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            window.URL.revokeObjectURL(url);

            showSuccessNotification(
                "Laporan SHU berhasil diunduh! Buka file HTML dan print ke PDF di browser.",
            );
        } catch (error: any) {
            console.error("❌ Error generating PDF:", error);
            alert(`Gagal membuat PDF: ${error.message}`);
        }
    }
</script>

<svelte:head>
    <title>SHU Report - Koperasi Backoffice</title>
</svelte:head>

<div class="p-6">
    <!-- Header -->
    <div class="flex justify-between items-center mb-6">
        <div>
            <h1 class="text-2xl font-bold text-gray-900">
                {canManageSHU ? "Kelola Laporan SHU" : "SHU Saya"}
            </h1>
            <p class="text-gray-600">
                {canManageSHU
                    ? "Kelola laporan Sisa Hasil Usaha koperasi"
                    : "Lihat riwayat dan generate SHU pribadi Anda"}
            </p>
        </div>

        {#if canManageSHU}
            <div class="flex space-x-3">
                <button
                    on:click={openGenerateModal}
                    class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition-colors"
                >
                    Generate Manual
                </button>
                <button
                    on:click={openAutoGenerateModal}
                    class="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600 transition-colors"
                >
                    Generate Otomatis
                </button>
            </div>
        {:else}
            <button
                on:click={openUserGenerateModal}
                class="bg-purple-500 text-white px-4 py-2 rounded hover:bg-purple-600 transition-colors"
            >
                Generate SHU Saya
            </button>
        {/if}
    </div>

    <!-- Main Content -->
    {#if canManageSHU}
        <!-- Admin/Super Admin View: SHU Records Management -->
        <div class="bg-white rounded-lg shadow">
            <div class="p-4 sm:p-6 border-b border-gray-200">
                <h2 class="text-xl font-semibold">Daftar Laporan SHU</h2>
            </div>

            {#if shuRecords.length === 0}
                <div class="p-8 text-center text-gray-500">
                    <p>Belum ada laporan SHU yang tersedia</p>
                    <div class="mt-4 space-x-2">
                        <button
                            on:click={openGenerateModal}
                            class="text-blue-500 hover:text-blue-600"
                        >
                            Generate manual
                        </button>
                        <span class="text-gray-300">atau</span>
                        <button
                            on:click={openAutoGenerateModal}
                            class="text-green-500 hover:text-green-600"
                        >
                            Generate otomatis
                        </button>
                    </div>
                </div>
            {:else}
                <div class="overflow-x-auto">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th
                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                >
                                    Tahun
                                </th>
                                <th
                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                >
                                    Total SHU
                                </th>
                                <th
                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                >
                                    Status
                                </th>
                                <th
                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                >
                                    Tanggal Dibuat
                                </th>
                                <th
                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                >
                                    Aksi
                                </th>
                            </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200">
                            {#each shuRecords as shu, index}
                                <tr class="hover:bg-gray-50">
                                    <td
                                        class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"
                                    >
                                        {shu.tahun}
                                    </td>
                                    <td
                                        class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"
                                    >
                                        {formatCurrency(shu.total_shu)}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <span
                                            class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium {shu.status ===
                                            'final'
                                                ? 'bg-green-100 text-green-800'
                                                : 'bg-yellow-100 text-yellow-800'}"
                                        >
                                            {shu.status === "final"
                                                ? "Final"
                                                : "Draft"}
                                        </span>
                                    </td>
                                    <td
                                        class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"
                                    >
                                        {formatDate(shu.created_at)}
                                    </td>
                                    <td
                                        class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 space-x-2"
                                    >
                                        <button
                                            on:click={() =>
                                                openDetailModal(shu)}
                                            class="text-blue-600 hover:text-blue-900"
                                        >
                                            Detail
                                        </button>
                                        <button
                                            on:click={() => generatePDF(shu)}
                                            class="text-green-600 hover:text-green-900"
                                        >
                                            PDF
                                        </button>
                                        <button
                                            on:click={() => {
                                                console.log(
                                                    "🔍 Delete button clicked for SHU:",
                                                    shu,
                                                );
                                                console.log(
                                                    "🔍 SHU ID being passed:",
                                                    shu.id,
                                                );
                                                console.log(
                                                    "🔍 All SHU fields:",
                                                    Object.keys(shu),
                                                );

                                                // Try different possible ID field names
                                                const possibleId = shu.id;

                                                if (possibleId) {
                                                    deleteSHURecord(possibleId);
                                                } else {
                                                    // If no ID field exists, show user which SHU they're trying to delete
                                                    const confirmMessage = `Apakah Anda yakin ingin menghapus laporan SHU tahun ${shu.tahun} dengan total ${formatCurrency(shu.total_shu)}?\n\nPeringatan: ID tidak ditemukan, sistem akan mencoba menghapus berdasarkan tahun.`;

                                                    if (
                                                        confirm(confirmMessage)
                                                    ) {
                                                        deleteSHURecordByYear(
                                                            shu.tahun,
                                                        );
                                                    }
                                                }
                                            }}
                                            class="text-red-600 hover:text-red-900"
                                        >
                                            Hapus
                                        </button>
                                    </td>
                                </tr>
                            {/each}
                        </tbody>
                    </table>
                </div>
            {/if}
        </div>
    {:else}
        <!-- Member View: Personal SHU History -->
        <div class="bg-white rounded-lg shadow">
            <div
                class="p-4 sm:p-6 border-b border-gray-200 flex justify-between items-center"
            >
                <div>
                    <h2 class="text-xl font-semibold">Riwayat SHU Saya</h2>
                    <p class="text-sm text-gray-600 mt-1">
                        Lihat riwayat SHU yang pernah Anda terima
                    </p>
                </div>
                <div class="flex gap-2">
                    <button
                        on:click={() => {
                            showUserSaveModal = true;
                        }}
                        class="px-3 py-2 sm:py-1 text-sm bg-purple-100 hover:bg-purple-200 text-purple-700 rounded-md transition-colors"
                        disabled={savingUserSHU}
                    >
                        💾 Simpan SHU
                    </button>
                    <button
                        on:click={refreshUserData}
                        class="px-3 py-2 sm:py-1 text-sm bg-gray-100 hover:bg-gray-200 rounded-md transition-colors"
                    >
                        🔄 Refresh
                    </button>
                </div>
            </div>

            {#if userShuHistory.length === 0}
                <div class="p-8 text-center text-gray-500">
                    <p>Belum ada riwayat SHU tersimpan untuk akun Anda</p>
                    <div
                        class="mt-4 p-4 bg-blue-50 rounded-lg text-sm text-blue-700"
                    >
                        <p class="font-medium mb-2">ℹ️ Cara Mendapatkan SHU:</p>
                        <ul class="text-left space-y-1">
                            <li>
                                • Klik tombol "💾 Simpan SHU" untuk menyimpan
                                SHU tahunan Anda
                            </li>
                            <li>
                                • SHU dihitung berdasarkan kontribusi simpanan
                                dan transaksi Anda
                            </li>
                            <li>
                                • Hasil tersimpan akan muncul di riwayat dengan
                                status draft/final
                            </li>
                            <li>
                                • Jika tombol tidak berfungsi, hubungi admin
                            </li>
                        </ul>
                    </div>
                    <div class="flex gap-2 justify-center mt-4">
                        <button
                            on:click={() => {
                                showUserSaveModal = true;
                            }}
                            class="px-4 py-2 bg-purple-500 text-white rounded hover:bg-purple-600 transition-colors"
                        >
                            💾 Simpan SHU Saya
                        </button>
                        <button
                            on:click={openUserGenerateModal}
                            class="px-4 py-2 text-purple-500 border border-purple-500 rounded hover:bg-purple-50 transition-colors"
                        >
                            🧮 Generate SHU (Legacy)
                        </button>
                    </div>
                </div>
            {:else}
                <div class="overflow-x-auto">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th
                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                >
                                    Periode
                                </th>
                                <th
                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                >
                                    Jasa Modal
                                </th>
                                <th
                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                >
                                    Jasa Usaha
                                </th>
                                <th
                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                >
                                    Total SHU
                                </th>
                                <th
                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                >
                                    Status
                                </th>
                                <th
                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                >
                                    Tanggal
                                </th>
                                <th
                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                >
                                    Aksi
                                </th>
                            </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200">
                            {#each userShuHistory as userShu, index}
                                <tr class="hover:bg-gray-50">
                                    <td
                                        class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"
                                    >
                                        {userShu.shu?.tahun ||
                                            userShu.periode ||
                                            userShu.tahun ||
                                            userShu.year ||
                                            "N/A"}
                                    </td>
                                    <td
                                        class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"
                                    >
                                        {formatCurrency(
                                            userShu.jumlah_modal ||
                                                userShu.jasa_modal ||
                                                userShu.JasaModal ||
                                                0,
                                        )}
                                    </td>
                                    <td
                                        class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"
                                    >
                                        {formatCurrency(
                                            userShu.jumlah_usaha ||
                                                userShu.jasa_usaha ||
                                                userShu.JasaUsaha ||
                                                0,
                                        )}
                                    </td>
                                    <td
                                        class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"
                                    >
                                        {formatCurrency(
                                            userShu.shu_diterima ||
                                                userShu.total_shu_anggota ||
                                                userShu.TotalSHUAnggota ||
                                                userShu.total_shu ||
                                                userShu.TotalSHU ||
                                                0,
                                        )}
                                    </td>
                                    <td
                                        class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"
                                    >
                                        <span
                                            class="inline-flex px-2 py-1 text-xs font-semibold rounded-full {userShu
                                                .shu?.status === 'final'
                                                ? 'bg-green-100 text-green-800'
                                                : 'bg-yellow-100 text-yellow-800'}"
                                        >
                                            {userShu.shu?.status === "final"
                                                ? "Final"
                                                : "Draft"}
                                        </span>
                                    </td>
                                    <td
                                        class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"
                                    >
                                        {formatDate(
                                            userShu.created_at ||
                                                userShu.CreatedAt ||
                                                userShu.tanggal_generate ||
                                                userShu.TanggalGenerate ||
                                                new Date().toISOString(),
                                        )}
                                    </td>
                                    <td
                                        class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"
                                    >
                                        {#if userShu.shu?.tahun}
                                            <button
                                                on:click={() => {
                                                    userSaveTahun =
                                                        userShu.shu.tahun;
                                                    showUserSaveModal = true;
                                                }}
                                                class="text-blue-600 hover:text-blue-700 text-sm"
                                                disabled={savingUserSHU}
                                            >
                                                💾 Simpan Ulang
                                            </button>
                                        {/if}
                                    </td>
                                </tr>
                            {/each}
                        </tbody>
                    </table>
                </div>
            {/if}
        </div>
    {/if}
</div>

<!-- Generate SHU Modal -->
{#if showGenerateModal}
    <div
        class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
    >
        <div
            class="bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto"
        >
            <div class="p-4 sm:p-6 border-b border-gray-200">
                <h3 class="text-lg font-semibold">Generate Laporan SHU</h3>
            </div>

            <form
                on:submit|preventDefault={generateSHUReport}
                class="p-4 sm:p-6 space-y-4"
            >
                <div>
                    <label
                        for="tahun"
                        class="block text-sm font-medium text-gray-700 mb-1"
                    >
                        Tahun
                    </label>
                    <input
                        type="number"
                        id="tahun"
                        bind:value={generateForm.tahun}
                        min="2020"
                        max="2030"
                        class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        required
                    />
                </div>

                <div>
                    <label
                        for="total_shu_koperasi"
                        class="block text-sm font-medium text-gray-700 mb-1"
                    >
                        Total SHU Koperasi
                    </label>
                    <input
                        type="number"
                        id="total_shu_koperasi"
                        bind:value={generateForm.total_shu_koperasi}
                        min="0"
                        step="1000"
                        class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        required
                    />
                </div>

                <div class="flex flex-col sm:flex-row justify-end space-y-2 sm:space-y-0 sm:space-x-3 pt-4">
                    <button
                        type="button"
                        on:click={closeModals}
                        class="w-full sm:w-auto px-4 py-3 sm:py-2 text-gray-700 bg-gray-200 rounded hover:bg-gray-300 transition-colors"
                    >
                        Batal
                    </button>
                    <button
                        type="submit"
                        class="w-full sm:w-auto px-4 py-3 sm:py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors"
                    >
                        Generate
                    </button>
                </div>
            </form>

            <!-- Generated Report Display -->
            {#if generatedReport}
                <div class="p-4 sm:p-6 border-t border-gray-200 bg-gray-50">
                    <h4 class="text-lg font-semibold mb-4">
                        Hasil Generate SHU
                    </h4>

                    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 gap-4 mb-4">
                        <div>
                            <p class="text-sm text-gray-600">Tahun</p>
                            <p class="font-semibold">{generatedReport.tahun}</p>
                        </div>
                        <div>
                            <p class="text-sm text-gray-600">
                                Total SHU Koperasi
                            </p>
                            <p class="font-semibold">
                                {formatCurrency(
                                    generatedReport.total_shu_koperasi,
                                )}
                            </p>
                        </div>
                        <div>
                            <p class="text-sm text-gray-600">
                                Persentase Jasa Modal
                            </p>
                            <p class="font-semibold">
                                {generatedReport.persen_jasa_modal}%
                            </p>
                        </div>
                        <div>
                            <p class="text-sm text-gray-600">
                                Persentase Jasa Usaha
                            </p>
                            <p class="font-semibold">
                                {generatedReport.persen_jasa_usaha}%
                            </p>
                        </div>
                        <div>
                            <p class="text-sm text-gray-600">Total Simpanan</p>
                            <p class="font-semibold">
                                {formatCurrency(
                                    generatedReport.total_simpanan_all,
                                )}
                            </p>
                        </div>
                        <div>
                            <p class="text-sm text-gray-600">Total Penjualan</p>
                            <p class="font-semibold">
                                {formatCurrency(
                                    generatedReport.total_penjualan_all,
                                )}
                            </p>
                        </div>
                    </div>

                    <div class="mb-4">
                        <h5 class="font-semibold mb-2">
                            Detail Anggota ({generatedReport.detail_anggota
                                .length} orang)
                        </h5>
                        <div class="max-h-40 overflow-y-auto">
                            <table class="min-w-full text-sm">
                                <thead class="bg-white">
                                    <tr>
                                        <th class="px-2 py-1 text-left"
                                            >Email</th
                                        >
                                        <th class="px-2 py-1 text-left"
                                            >Simpanan</th
                                        >
                                        <th class="px-2 py-1 text-left"
                                            >Penjualan</th
                                        >
                                        <th class="px-2 py-1 text-left"
                                            >Total SHU</th
                                        >
                                    </tr>
                                </thead>
                                <tbody>
                                    {#each generatedReport.detail_anggota as member}
                                        <tr class="border-t">
                                            <td class="px-2 py-1"
                                                >{member.email}</td
                                            >
                                            <td class="px-2 py-1"
                                                >{formatCurrency(
                                                    member.total_simpanan,
                                                )}</td
                                            >
                                            <td class="px-2 py-1"
                                                >{formatCurrency(
                                                    member.total_penjualan,
                                                )}</td
                                            >
                                            <td class="px-2 py-1 font-semibold"
                                                >{formatCurrency(
                                                    member.total_shu_anggota,
                                                )}</td
                                            >
                                        </tr>
                                    {/each}
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <form
                        on:submit|preventDefault={saveSHUReport}
                        class="space-y-4"
                    >
                        <div>
                            <label
                                for="status"
                                class="block text-sm font-medium text-gray-700 mb-1"
                            >
                                Status
                            </label>
                            <select
                                id="status"
                                bind:value={saveForm.status}
                                class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                            >
                                <option value="draft">Draft</option>
                                <option value="final">Final</option>
                            </select>
                        </div>

                        <div class="flex justify-end space-x-3">
                            <button
                                type="button"
                                on:click={closeModals}
                                class="px-4 py-2 text-gray-700 bg-gray-200 rounded hover:bg-gray-300 transition-colors"
                            >
                                Batal
                            </button>
                            <button
                                type="submit"
                                class="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition-colors"
                            >
                                Simpan Laporan
                            </button>
                        </div>
                    </form>
                </div>
            {/if}
        </div>
    </div>
{/if}

<!-- Automated Generate SHU Modal -->
{#if showAutoGenerateModal}
    <div
        class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
    >
        <div
            class="bg-white rounded-lg max-w-3xl w-full max-h-[90vh] overflow-y-auto"
        >
            <div class="p-4 sm:p-6 border-b border-gray-200">
                <h3 class="text-lg font-semibold">Generate SHU Otomatis</h3>
                <p class="text-sm text-gray-600 mt-1">
                    Masukkan data keuangan untuk perhitungan SHU otomatis
                </p>
            </div>

            <form
                on:submit|preventDefault={generateAutoSHUReport}
                class="p-4 sm:p-6 space-y-4"
            >
                <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 gap-4">
                    <div>
                        <label
                            for="tahun_auto"
                            class="block text-sm font-medium text-gray-700 mb-1"
                        >
                            Tahun
                        </label>
                        <input
                            type="number"
                            id="tahun_auto"
                            bind:value={autoGenerateForm.tahun}
                            min="2020"
                            max="2030"
                            class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500"
                            required
                        />
                    </div>

                    <div>
                        <label
                            for="beban_operasional"
                            class="block text-sm font-medium text-gray-700 mb-1"
                        >
                            Beban Operasional
                        </label>
                        <input
                            type="number"
                            id="beban_operasional"
                            bind:value={autoGenerateForm.beban_operasional}
                            min="0"
                            step="1000"
                            class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500"
                            required
                        />
                    </div>

                    <div>
                        <label
                            for="beban_non_operasional"
                            class="block text-sm font-medium text-gray-700 mb-1"
                        >
                            Beban Non-Operasional
                        </label>
                        <input
                            type="number"
                            id="beban_non_operasional"
                            bind:value={autoGenerateForm.beban_non_operasional}
                            min="0"
                            step="1000"
                            class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500"
                            required
                        />
                    </div>

                    <div>
                        <label
                            for="beban_pajak"
                            class="block text-sm font-medium text-gray-700 mb-1"
                        >
                            Beban Pajak
                        </label>
                        <input
                            type="number"
                            id="beban_pajak"
                            bind:value={autoGenerateForm.beban_pajak}
                            min="0"
                            step="1000"
                            class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500"
                            required
                        />
                    </div>
                </div>

                <!-- Information Note -->
                <div class="p-4 bg-blue-50 rounded-lg">
                    <h5 class="font-semibold text-blue-800 mb-2">
                        ℹ️ Informasi Perhitungan
                    </h5>
                    <div class="text-sm text-blue-700 space-y-1">
                        <p>
                            • Pendapatan operasional dan non-operasional akan
                            dihitung otomatis oleh sistem
                        </p>
                        <p>
                            • Formula: SHU Total = (Pendapatan Operasional +
                            Pendapatan Non-Operasional) - (Beban Operasional +
                            Beban Non-Operasional + Beban Pajak)
                        </p>
                        <p>
                            • Total beban yang akan dikurangkan: <span
                                class="font-medium"
                                >{formatCurrency(
                                    autoGenerateForm.beban_operasional +
                                        autoGenerateForm.beban_non_operasional +
                                        autoGenerateForm.beban_pajak,
                                )}</span
                            >
                        </p>
                    </div>
                </div>

                <div class="flex flex-col sm:flex-row justify-end space-y-2 sm:space-y-0 sm:space-x-3 pt-4">
                    <button
                        type="button"
                        on:click={closeModals}
                        class="w-full sm:w-auto px-4 py-3 sm:py-2 text-gray-700 bg-gray-200 rounded hover:bg-gray-300 transition-colors"
                    >
                        Batal
                    </button>
                    <button
                        type="submit"
                        class="w-full sm:w-auto px-4 py-3 sm:py-2 bg-green-500 text-white rounded hover:bg-green-600 transition-colors"
                    >
                        Generate Otomatis
                    </button>
                </div>
            </form>

            <!-- Auto Generated Report Display -->
            {#if autoGeneratedReport}
                <div class="p-4 sm:p-6 border-t border-gray-200 bg-green-50">
                    <h4 class="text-lg font-semibold mb-4">
                        🎉 Hasil Generate SHU Otomatis
                    </h4>

                    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 gap-4 mb-4">
                        <div>
                            <p class="text-sm text-gray-600">Tahun</p>
                            <p class="font-semibold">
                                {autoGeneratedReport.tahun}
                            </p>
                        </div>
                        <div>
                            <p class="text-sm text-gray-600">
                                Total SHU Koperasi
                            </p>
                            <p class="font-semibold text-green-600">
                                {formatCurrency(
                                    autoGeneratedReport.total_shu_koperasi,
                                )}
                            </p>
                        </div>
                        <div>
                            <p class="text-sm text-gray-600">
                                Pendapatan Operasional
                            </p>
                            <p class="font-semibold">
                                {formatCurrency(
                                    autoGeneratedReport.pendapatan_operasional,
                                )}
                            </p>
                        </div>
                        <div>
                            <p class="text-sm text-gray-600">
                                Pendapatan Non-Operasional
                            </p>
                            <p class="font-semibold">
                                {formatCurrency(
                                    autoGeneratedReport.pendapatan_non_operasional,
                                )}
                            </p>
                        </div>
                        <div>
                            <p class="text-sm text-gray-600">
                                Total Simpanan Semua Anggota
                            </p>
                            <p class="font-semibold">
                                {formatCurrency(
                                    autoGeneratedReport.total_simpanan_all,
                                )}
                            </p>
                        </div>
                        <div>
                            <p class="text-sm text-gray-600">
                                Total Penjualan Semua Anggota
                            </p>
                            <p class="font-semibold">
                                {formatCurrency(
                                    autoGeneratedReport.total_penjualan_all,
                                )}
                            </p>
                        </div>
                    </div>

                    <div class="mb-4">
                        <h5 class="font-semibold mb-2">Detail Keuangan:</h5>
                        <div
                            class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 gap-2 text-sm bg-white p-3 rounded"
                        >
                            <div class="flex justify-between">
                                <span class="text-green-700"
                                    >Pendapatan Operasional:</span
                                >
                                <span class="font-medium"
                                    >{formatCurrency(
                                        autoGeneratedReport.pendapatan_operasional,
                                    )}</span
                                >
                            </div>
                            <div class="flex justify-between">
                                <span class="text-green-700"
                                    >Pendapatan Non-Operasional:</span
                                >
                                <span class="font-medium"
                                    >{formatCurrency(
                                        autoGeneratedReport.pendapatan_non_operasional,
                                    )}</span
                                >
                            </div>
                            <div class="flex justify-between">
                                <span class="text-red-700"
                                    >Beban Operasional:</span
                                >
                                <span class="font-medium"
                                    >({formatCurrency(
                                        autoGeneratedReport.beban_operasional,
                                    )})</span
                                >
                            </div>
                            <div class="flex justify-between">
                                <span class="text-red-700"
                                    >Beban Non-Operasional:</span
                                >
                                <span class="font-medium"
                                    >({formatCurrency(
                                        autoGeneratedReport.beban_non_operasional,
                                    )})</span
                                >
                            </div>
                            <div class="flex justify-between">
                                <span class="text-red-700">Beban Pajak:</span>
                                <span class="font-medium"
                                    >({formatCurrency(
                                        autoGeneratedReport.beban_pajak,
                                    )})</span
                                >
                            </div>
                            <div class="col-span-2 border-t pt-2 mt-2">
                                <div
                                    class="flex justify-between font-bold text-lg"
                                >
                                    <span>SHU Total:</span>
                                    <span class="text-green-600"
                                        >{formatCurrency(
                                            autoGeneratedReport.total_shu_koperasi,
                                        )}</span
                                    >
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="mb-4">
                        <h5 class="font-semibold mb-2">
                            Detail Pembagian SHU ({autoGeneratedReport
                                .detail_anggota.length} anggota)
                        </h5>
                        <div class="max-h-40 overflow-y-auto bg-white rounded">
                            <table class="min-w-full text-sm">
                                <thead class="bg-gray-100 sticky top-0">
                                    <tr>
                                        <th class="px-2 py-1 text-left"
                                            >Email</th
                                        >
                                        <th class="px-2 py-1 text-left"
                                            >Simpanan</th
                                        >
                                        <th class="px-2 py-1 text-left"
                                            >Penjualan</th
                                        >
                                        <th class="px-2 py-1 text-left"
                                            >Jasa Modal</th
                                        >
                                        <th class="px-2 py-1 text-left"
                                            >Jasa Usaha</th
                                        >
                                        <th class="px-2 py-1 text-left"
                                            >Total SHU</th
                                        >
                                    </tr>
                                </thead>
                                <tbody>
                                    {#each autoGeneratedReport.detail_anggota as member}
                                        <tr class="border-t">
                                            <td class="px-2 py-1"
                                                >{member.email}</td
                                            >
                                            <td class="px-2 py-1"
                                                >{formatCurrency(
                                                    member.total_simpanan,
                                                )}</td
                                            >
                                            <td class="px-2 py-1"
                                                >{formatCurrency(
                                                    member.total_penjualan,
                                                )}</td
                                            >
                                            <td class="px-2 py-1"
                                                >{formatCurrency(
                                                    member.jasa_modal,
                                                )}</td
                                            >
                                            <td class="px-2 py-1"
                                                >{formatCurrency(
                                                    member.jasa_usaha,
                                                )}</td
                                            >
                                            <td class="px-2 py-1 font-semibold"
                                                >{formatCurrency(
                                                    member.total_shu_anggota,
                                                )}</td
                                            >
                                        </tr>
                                    {/each}
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="flex justify-end space-x-3">
                        <button
                            type="button"
                            on:click={closeModals}
                            class="px-4 py-2 text-gray-700 bg-gray-200 rounded hover:bg-gray-300 transition-colors"
                        >
                            Tutup
                        </button>
                        <button
                            type="button"
                            on:click={saveAutoSHUReport}
                            class="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition-colors"
                        >
                            💾 Simpan ke Daftar SHU
                        </button>
                    </div>
                </div>
            {/if}
        </div>
    </div>
{/if}

<!-- User Generate SHU Modal -->
{#if showUserGenerateModal}
    <div
        class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
    >
        <div class="bg-white rounded-lg max-w-md w-full">
            <div class="p-4 sm:p-6 border-b border-gray-200">
                <h3 class="text-lg font-semibold">Generate SHU Pribadi</h3>
                <p class="text-sm text-gray-600 mt-1">
                    Generate laporan SHU berdasarkan aktivitas simpan-pinjam
                    Anda
                </p>
            </div>

            <div class="p-4 sm:p-6">
                <div class="mb-4 p-4 bg-purple-50 rounded-lg">
                    <h5 class="font-semibold text-purple-800 mb-2">
                        Informasi
                    </h5>
                    <ul class="text-sm text-purple-700 space-y-1">
                        <li>
                            • SHU dihitung berdasarkan simpanan dan transaksi
                            Anda
                        </li>
                        <li>
                            • Perhitungan menggunakan formula yang telah
                            ditetapkan koperasi
                        </li>
                        <li>• Hasil akan ditampilkan di riwayat SHU Anda</li>
                    </ul>
                </div>

                <div class="flex flex-col sm:flex-row justify-end space-y-2 sm:space-y-0 sm:space-x-3">
                    <button
                        type="button"
                        on:click={closeModals}
                        class="w-full sm:w-auto px-4 py-3 sm:py-2 text-gray-700 bg-gray-200 rounded hover:bg-gray-300 transition-colors"
                    >
                        Batal
                    </button>
                    <button
                        type="button"
                        on:click={generateUserSHU}
                        class="w-full sm:w-auto px-4 py-3 sm:py-2 bg-purple-500 text-white rounded hover:bg-purple-600 transition-colors"
                    >
                        Generate SHU Saya
                    </button>
                </div>
            </div>
        </div>
    </div>
{/if}

<!-- User Save SHU Modal -->
{#if showUserSaveModal}
    <div
        class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
    >
        <div class="bg-white rounded-lg max-w-md w-full">
            <div class="p-4 sm:p-6 border-b border-gray-200">
                <h3 class="text-lg font-semibold">Simpan SHU Pribadi</h3>
                <p class="text-sm text-gray-600 mt-1">
                    Simpan laporan SHU Anda ke dalam database
                </p>
            </div>

            <div class="p-4 sm:p-6">
                <div class="mb-4">
                    <label
                        for="userSaveTahun"
                        class="block text-sm font-medium text-gray-700 mb-2"
                    >
                        Tahun SHU
                    </label>
                    <input
                        id="userSaveTahun"
                        type="number"
                        bind:value={userSaveTahun}
                        min="2020"
                        max="2030"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-purple-500"
                        placeholder="Masukkan tahun (contoh: 2024)"
                    />
                </div>

                <div class="mb-4 p-4 bg-purple-50 rounded-lg">
                    <h5 class="font-semibold text-purple-800 mb-2">
                        Informasi
                    </h5>
                    <ul class="text-sm text-purple-700 space-y-1">
                        <li>
                            • SHU akan dihitung dan disimpan berdasarkan data
                            tahun yang dipilih
                        </li>
                        <li>
                            • Pastikan Anda sudah memiliki aktivitas di tahun
                            tersebut
                        </li>
                        <li>
                            • Data yang disimpan akan muncul di riwayat SHU Anda
                        </li>
                    </ul>
                </div>

                <div class="flex flex-col sm:flex-row justify-end space-y-2 sm:space-y-0 sm:space-x-3">
                    <button
                        type="button"
                        on:click={closeModals}
                        class="w-full sm:w-auto px-4 py-3 sm:py-2 text-gray-700 bg-gray-200 rounded hover:bg-gray-300 transition-colors"
                        disabled={savingUserSHU}
                    >
                        Batal
                    </button>
                    <button
                        type="button"
                        on:click={async () => {
                            savingUserSHU = true;
                            await saveUserSHU(userSaveTahun);
                            savingUserSHU = false;
                            closeModals();
                        }}
                        class="w-full sm:w-auto px-4 py-3 sm:py-2 bg-purple-500 text-white rounded hover:bg-purple-600 transition-colors disabled:opacity-50"
                        disabled={savingUserSHU || !userSaveTahun}
                    >
                        {savingUserSHU ? "Menyimpan..." : "Simpan SHU"}
                    </button>
                </div>
            </div>
        </div>
    </div>
{/if}

<!-- Detail SHU Modal -->
{#if showDetailModal && selectedSHU}
    <div
        class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
    >
        <div
            class="bg-white rounded-lg max-w-4xl w-full max-h-[90vh] overflow-y-auto"
        >
            <div class="p-4 sm:p-6 border-b border-gray-200">
                <h3 class="text-lg font-semibold">
                    Detail Laporan SHU {selectedSHU.tahun}
                </h3>
            </div>

            <div class="p-4 sm:p-6 space-y-6">
                <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 gap-4">
                    <div>
                        <p class="text-sm text-gray-600">Tahun</p>
                        <p class="font-semibold">{selectedSHU.tahun}</p>
                    </div>
                    <div>
                        <p class="text-sm text-gray-600">Total SHU</p>
                        <p class="font-semibold">
                            {formatCurrency(selectedSHU.total_shu)}
                        </p>
                    </div>
                    <div>
                        <p class="text-sm text-gray-600">Status</p>
                        <span
                            class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium {selectedSHU.status ===
                            'final'
                                ? 'bg-green-100 text-green-800'
                                : 'bg-yellow-100 text-yellow-800'}"
                        >
                            {selectedSHU.status === "final" ? "Final" : "Draft"}
                        </span>
                    </div>
                    <div>
                        <p class="text-sm text-gray-600">Tanggal Dibuat</p>
                        <p class="font-semibold">
                            {formatDate(selectedSHU.created_at)}
                        </p>
                    </div>
                </div>

                {#if selectedSHU.shu_report}
                    <div class="border-t pt-6">
                        <h4 class="text-lg font-semibold mb-4">
                            Detail Perhitungan
                        </h4>

                        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 gap-4 mb-6">
                            <div>
                                <p class="text-sm text-gray-600">
                                    Persentase Jasa Modal
                                </p>
                                <p class="font-semibold">
                                    {selectedSHU.shu_report.persen_jasa_modal}%
                                </p>
                            </div>
                            <div>
                                <p class="text-sm text-gray-600">
                                    Persentase Jasa Usaha
                                </p>
                                <p class="font-semibold">
                                    {selectedSHU.shu_report.persen_jasa_usaha}%
                                </p>
                            </div>
                            <div>
                                <p class="text-sm text-gray-600">
                                    Total Simpanan Semua Anggota
                                </p>
                                <p class="font-semibold">
                                    {formatCurrency(
                                        selectedSHU.shu_report
                                            .total_simpanan_all,
                                    )}
                                </p>
                            </div>
                            <div>
                                <p class="text-sm text-gray-600">
                                    Total Penjualan Semua Anggota
                                </p>
                                <p class="font-semibold">
                                    {formatCurrency(
                                        selectedSHU.shu_report
                                            .total_penjualan_all,
                                    )}
                                </p>
                            </div>
                        </div>

                        <h5 class="font-semibold mb-4">
                            Detail Anggota ({selectedSHU.shu_report
                                .detail_anggota.length} orang)
                        </h5>
                        <div class="overflow-x-auto">
                            <table
                                class="min-w-full text-sm border border-gray-200"
                            >
                                <thead class="bg-gray-50">
                                    <tr>
                                        <th class="px-4 py-2 text-left border-b"
                                            >Email</th
                                        >
                                        <th class="px-4 py-2 text-left border-b"
                                            >Simpanan</th
                                        >
                                        <th class="px-4 py-2 text-left border-b"
                                            >Penjualan</th
                                        >
                                        <th class="px-4 py-2 text-left border-b"
                                            >Jasa Modal</th
                                        >
                                        <th class="px-4 py-2 text-left border-b"
                                            >Jasa Usaha</th
                                        >
                                        <th class="px-4 py-2 text-left border-b"
                                            >Total SHU</th
                                        >
                                    </tr>
                                </thead>
                                <tbody>
                                    {#each selectedSHU.shu_report.detail_anggota as member}
                                        <tr class="border-b">
                                            <td class="px-4 py-2"
                                                >{member.email}</td
                                            >
                                            <td class="px-4 py-2"
                                                >{formatCurrency(
                                                    member.total_simpanan,
                                                )}</td
                                            >
                                            <td class="px-4 py-2"
                                                >{formatCurrency(
                                                    member.total_penjualan,
                                                )}</td
                                            >
                                            <td class="px-4 py-2"
                                                >{formatCurrency(
                                                    member.jasa_modal,
                                                )}</td
                                            >
                                            <td class="px-4 py-2"
                                                >{formatCurrency(
                                                    member.jasa_usaha,
                                                )}</td
                                            >
                                            <td class="px-4 py-2 font-semibold"
                                                >{formatCurrency(
                                                    member.total_shu_anggota,
                                                )}</td
                                            >
                                        </tr>
                                    {/each}
                                </tbody>
                            </table>
                        </div>
                    </div>
                {/if}

                <div class="flex justify-end space-x-3 pt-4">
                    <button
                        on:click={() => generatePDF(selectedSHU!)}
                        class="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition-colors"
                    >
                        Download PDF
                    </button>
                    <button
                        on:click={closeModals}
                        class="px-4 py-2 text-gray-700 bg-gray-200 rounded hover:bg-gray-300 transition-colors"
                    >
                        Tutup
                    </button>
                </div>
            </div>
        </div>
    </div>
{/if}
