<script lang="ts">
    import type {
        SHURecord,
        SHUReport,
        SHUGenerateRequest,
        SHUSaveRequest,
        SHUAutoGenerateRequest,
        SHUAutoReport,
        SHUAutoSaveRequest,
        SHUAnggotaSaveRequest,
        SHUAnggotaRecord,
        SHUAnggotaSaveResponse,
        SHUAnggotaHistoryResponse,
    } from "$lib/types";
    import { invalidateAll } from "$app/navigation";
    import axios from "$lib/api";
    import { onMount } from "svelte";
    import {
        showSuccess,
        showError,
        showWarning,
    } from "$lib/stores/notifications";
    import { formatCurrency, formatDate } from "$lib/utils";

    export let data;

    // Safe date formatting helper
    function safeDateFormat(shuRecord: any): string {
        const dateValue =
            shuRecord.CreatedAt ||
            shuRecord.created_at ||
            shuRecord.tanggal_dibuat ||
            shuRecord.date_created;
        if (!dateValue) {
            console.warn(
                "No date field found in SHU record:",
                Object.keys(shuRecord),
            );
            return "Tanggal tidak tersedia";
        }
        return formatDate(dateValue);
    }

    let shuRecords: SHURecord[] = data.shuRecords || [];
    let userShuHistory: any[] = data.userShuHistory || [];
    const currentUser = data.currentUser;
    const canManageSHU = data.canManageSHU || false;

    // Reactive updates when data changes
    $: {
        shuRecords = data.shuRecords || [];
        userShuHistory = data.userShuHistory || [];
    }

    // Manual refresh function
    async function refreshUserData() {
        try {
            await invalidateAll();
            userShuHistory = data.userShuHistory || [];
        } catch (error) {
            console.error("❌ Refresh failed:", error);
        }
    }

    // Modal states
    let showGenerateModal = false;
    let showAutoGenerateModal = false;
    let showDetailModal = false;
    let showUserGenerateModal = false;
    let selectedSHU: SHURecord | null = null;
    let generatedReport: SHUReport | null = null;
    let autoGeneratedReport: SHUAutoReport | null = null;

    // Form data
    let generateForm: SHUGenerateRequest = {
        tahun: new Date().getFullYear(),
        total_shu_koperasi: 0,
    };

    // Variables for automated SHU generation - only expenses needed
    let autoGenerateForm: SHUAutoGenerateRequest = {
        tahun: new Date().getFullYear(),
        beban_operasional: 0,
        beban_non_operasional: 0,
        beban_pajak: 0,
    };

    let saveForm: SHUSaveRequest = {
        tahun: new Date().getFullYear(),
        total_shu: 0,
        status: "draft",
    };

    // User SHU save variables
    let userSaveTahun: number = new Date().getFullYear();
    let showUserSaveModal = false;
    let savingUserSHU = false;

    // Utility functions
    function showSuccessNotification(message: string) {
        showSuccess(message);
    }

    // Modal functions
    function openGenerateModal() {
        generateForm = {
            tahun: new Date().getFullYear(),
            total_shu_koperasi: 0,
        };
        generatedReport = null;
        showGenerateModal = true;
    }

    function openAutoGenerateModal() {
        autoGenerateForm = {
            tahun: new Date().getFullYear(),
            beban_operasional: 0,
            beban_non_operasional: 0,
            beban_pajak: 0,
        };
        autoGeneratedReport = null;
        showAutoGenerateModal = true;
    }

    function openUserGenerateModal() {
        showUserGenerateModal = true;
    }

    function openDetailModal(shu: SHURecord) {
        selectedSHU = shu;
        showDetailModal = true;

        // If shu_report is missing, try to fetch detailed data
        if (!shu.shu_report && canManageSHU) {
            fetchDetailedSHUData(shu);
        }
    }

    async function fetchDetailedSHUData(shu: SHURecord) {
        try {
            // Generate the detailed report using the auto-generate endpoint
            await generateDetailedSHUReport(shu);
        } catch (error: any) {
            console.error("Error fetching detailed SHU data:", error);
        }
    }

    async function generateDetailedSHUReport(shu: SHURecord) {
        try {
            // Use the correct auto-generate endpoint
            const response = await axios.post("/shu/generate-auto", {
                tahun: shu.tahun,
                beban_operasional: shu.beban_operasional || 0,
                beban_non_operasional: shu.beban_non_operasional || 0,
                beban_pajak: shu.beban_pajak || 0,
            });

            if (response.data.data && response.data.data.detail_anggota) {
                // Update the existing SHU record with detailed data
                const updateData = {
                    shu_report: {
                        persen_jasa_modal:
                            response.data.data.persen_jasa_modal || 0,
                        persen_jasa_usaha:
                            response.data.data.persen_jasa_usaha || 0,
                        total_simpanan_all:
                            response.data.data.total_simpanan_all || 0,
                        total_penjualan_all:
                            response.data.data.total_penjualan_all || 0,
                        detail_anggota: response.data.data.detail_anggota || [],
                    },
                };

                try {
                    // Try to update the existing record
                    const updateResponse = await axios.put(
                        `/shu/${shu.ID || shu.id}`,
                        updateData,
                    );

                    // Update the local selectedSHU with the new detailed data
                    selectedSHU = {
                        ...selectedSHU,
                        shu_report: updateData.shu_report,
                    };

                    showSuccessNotification(
                        `Detail SHU berhasil digenerate untuk ${response.data.data.detail_anggota.length} anggota!`,
                    );
                } catch (updateError: any) {
                    // Still update the display even if database update fails
                    selectedSHU = {
                        ...selectedSHU,
                        shu_report: updateData.shu_report,
                    };
                    showSuccessNotification(
                        `Detail SHU berhasil digenerate (tampilan saja): ${response.data.data.detail_anggota.length} anggota`,
                    );
                }
            }
        } catch (error: any) {
            console.error("❌ Error generating detailed SHU report:", error);
            showError(
                `Gagal generate detail SHU: ${error.response?.data?.message || error.message}`,
            );
        }
    }

    function closeModals() {
        showGenerateModal = false;
        showAutoGenerateModal = false;
        showDetailModal = false;
        showUserGenerateModal = false;
        showUserSaveModal = false;
        selectedSHU = null;
        generatedReport = null;
        autoGeneratedReport = null;
    }

    // SHU operations
    async function generateSHUReport() {
        try {
            const response = await axios.post("/shu/generate", generateForm);

            generatedReport = response.data.data;

            showSuccessNotification("Laporan SHU berhasil digenerate!");
        } catch (error: any) {
            console.error("❌ Error generating SHU report:", error);
            showError(
                error.response?.data?.message || error.message,
                "Generate Failed",
            );
        }
    }

    async function generateAutoSHUReport() {
        try {
            const response = await axios.post(
                "/shu/generate-auto",
                autoGenerateForm,
            );

            autoGeneratedReport = response.data.data;

            showSuccessNotification(
                "Laporan SHU otomatis berhasil digenerate!",
            );
        } catch (error: any) {
            console.error("❌ Error generating automated SHU report:", error);
            showError(
                `Gagal generate laporan SHU otomatis: ${error.response?.data?.message || error.message}`,
            );
        }
    }

    async function saveAutoSHUReport() {
        if (!autoGeneratedReport) {
            showWarning("Silakan generate laporan otomatis terlebih dahulu");
            return;
        }

        try {
            // Convert values with extra validation
            const totalSHU = Math.round(
                Number(autoGeneratedReport.total_shu_koperasi) || 0,
            );
            const tahun =
                Number(autoGeneratedReport.tahun) || new Date().getFullYear();
            const pendapatanOp = Math.round(
                Number(autoGeneratedReport.pendapatan_operasional) || 0,
            );
            const pendapatanNonOp = Math.round(
                Number(autoGeneratedReport.pendapatan_non_operasional) || 0,
            );
            const bebanOp = Math.round(
                Number(autoGeneratedReport.beban_operasional) || 0,
            );
            const bebanNonOp = Math.round(
                Number(autoGeneratedReport.beban_non_operasional) || 0,
            );
            const bebanPajak = Math.round(
                Number(autoGeneratedReport.beban_pajak) || 0,
            );

            // Check if SHU Total is valid for saving
            if (totalSHU <= 0) {
                showError(
                    `Tidak dapat menyimpan laporan SHU karena total SHU adalah ${formatCurrency(totalSHU)}.\n\nPastikan pendapatan lebih besar dari total beban untuk menghasilkan SHU positif.`,
                );
                return;
            }

            // Use the EXACT structure from API documentation
            const saveData = {
                tahun: tahun,
                pendapatan_operasional: pendapatanOp,
                pendapatan_non_operasional: pendapatanNonOp,
                beban_operasional: bebanOp,
                beban_non_operasional: bebanNonOp,
                beban_pajak: bebanPajak,
                total_shu: totalSHU, // This is the correct field name from API docs
                status: "draft",
                shu_report: autoGeneratedReport, // Include the detailed member breakdown
            };

            const response = await axios.post("/shu/save-auto", saveData);

            // Refresh data
            await invalidateAll();
            closeModals();
            showSuccessNotification(
                "Laporan SHU otomatis berhasil disimpan ke daftar!",
            );
        } catch (error: any) {
            console.error("Save failed:", error);
            console.error("❌ Error status:", error.response?.status);

            const errorMessage =
                error.response?.data?.message ||
                error.response?.data?.error ||
                error.message ||
                "Unknown error occurred";

            showError(`Gagal menyimpan laporan SHU otomatis: ${errorMessage}`);
        }
    }

    async function generateUserSHU() {
        try {
            // User SHU generation now requires year input according to API docs
            const currentYear = new Date().getFullYear();
            const requestData = {
                Tahun: currentYear,
                TotalSHUKoperasi: 0, // Try with the fields the error mentioned
            };

            const response = await axios.post(
                `/shu/user/${currentUser.id}/generate`,
                requestData,
            );

            // Refresh user history
            await invalidateAll();
            closeModals();
            showSuccessNotification("SHU pribadi berhasil digenerate!");
        } catch (error: any) {
            console.error("❌ Error generating user SHU:", error);
            console.error("❌ Error response:", error.response?.data);
            console.error("❌ Error status:", error.response?.status);

            // Handle specific error cases
            if (error.response?.status === 403) {
                showError(
                    "Access Denied: Anda tidak memiliki izin untuk generate SHU pribadi.\n\nKemungkinan penyebab:\n• Fitur belum aktif untuk user biasa\n• Perlu izin khusus dari admin\n• Role/permission tidak sesuai",
                );
                return;
            }

            if (error.response?.status === 401) {
                showError(
                    "Authentication Error: Sesi login Anda mungkin telah berakhir.\n\nSilakan refresh halaman dan login kembali.",
                );
                return;
            }

            // Try with 'tahun' field if current format fails
            if (error.response?.status === 400) {
                try {
                    const alternativeData = { tahun: new Date().getFullYear() };

                    const retryResponse = await axios.post(
                        `/shu/user/${currentUser.id}/generate`,
                        alternativeData,
                    );

                    await invalidateAll();
                    closeModals();
                    showSuccessNotification("SHU pribadi berhasil digenerate!");
                    return;
                } catch (retryError: any) {
                    console.error(
                        "❌ Alternative format also failed:",
                        retryError,
                    );
                }
            }

            const errorMessage =
                error.response?.data?.message ||
                error.response?.data?.error ||
                error.message ||
                "API endpoint may not be implemented";

            showError(
                `Gagal generate SHU pribadi: ${errorMessage}\n\nEndpoint: /shu/user/${currentUser.id}/generate\nStatus: ${error.response?.status || "Unknown"}`,
            );
        }
    }

    async function saveUserSHU(tahun: number) {
        try {
            // Validation
            if (!tahun || tahun < 2020 || tahun > 2030) {
                showError(
                    "Tahun tidak valid. Silakan masukkan tahun antara 2020-2030",
                );
                return;
            }

            if (!currentUser?.id) {
                showError(
                    "Error: User ID tidak ditemukan. Silakan login ulang.",
                );
                return;
            }

            const saveRequest: SHUAnggotaSaveRequest = {
                tahun: tahun,
            };

            const response = await axios.post<SHUAnggotaSaveResponse>(
                `/shu-anggota/user/${currentUser.id}/save`,
                saveRequest,
            );

            // Refresh user history to show the newly saved record
            await invalidateAll();

            showSuccessNotification(
                `SHU untuk tahun ${tahun} berhasil disimpan!`,
            );

            return response.data.data;
        } catch (error: any) {
            console.error("❌ Error saving user SHU:", error);
            console.error("❌ Error response:", error.response?.data);
            console.error("❌ Error status:", error.response?.status);

            // Handle specific error cases
            if (error.response?.status === 403) {
                showError(
                    "Access Denied: Anda tidak memiliki izin untuk menyimpan SHU pribadi.\n\nKemungkinan penyebab:\n• Fitur belum aktif\n• Role/permission tidak sesuai",
                );
                return;
            }

            if (error.response?.status === 401) {
                showError(
                    "Authentication Error: Sesi login Anda mungkin telah berakhir.\n\nSilakan refresh halaman dan login kembali.",
                );
                return;
            }

            if (error.response?.status === 400) {
                const errorMessage =
                    error.response?.data?.message ||
                    error.response?.data?.error ||
                    "Data request tidak valid";
                showError(
                    `Gagal menyimpan SHU: ${errorMessage}\n\nPastikan:\n• Tahun yang dipilih valid\n• Anda memiliki data transaksi di tahun tersebut`,
                );
                return;
            }

            if (error.response?.status === 404) {
                showError(
                    `SHU untuk tahun ${tahun} tidak ditemukan.\n\nKemungkinan penyebab:\n• Data SHU tahun ${tahun} belum dibuat oleh admin\n• Tidak ada transaksi di tahun tersebut`,
                );
                return;
            }

            const errorMessage =
                error.response?.data?.message ||
                error.response?.data?.error ||
                error.message ||
                "Unknown error occurred";

            showError(
                `Gagal menyimpan SHU pribadi: ${errorMessage}\n\nEndpoint: /shu-anggota/user/${currentUser.id}/save\nStatus: ${error.response?.status || "Unknown"}`,
            );
        }
    }

    async function saveSHUReport() {
        if (!generatedReport) {
            showWarning("Silakan generate laporan terlebih dahulu");
            return;
        }

        try {
            saveForm.tahun = generatedReport.tahun;
            saveForm.total_shu = generatedReport.total_shu_koperasi;

            // Include the detailed member breakdown
            const fullSHUData = {
                ...saveForm,
                shu_report: {
                    persen_jasa_modal: generatedReport.persen_jasa_modal || 0,
                    persen_jasa_usaha: generatedReport.persen_jasa_usaha || 0,
                    total_simpanan_all: generatedReport.total_simpanan_all || 0,
                    total_penjualan_all:
                        generatedReport.total_penjualan_all || 0,
                    detail_anggota: generatedReport.detail_anggota || [],
                },
            };

            await axios.post("/shu", fullSHUData);

            // Refresh data
            await invalidateAll();

            closeModals();
            showSuccessNotification(
                `Laporan SHU berhasil disimpan dengan detail ${generatedReport.detail_anggota?.length || 0} anggota!`,
            );
        } catch (error: any) {
            console.error("❌ Error saving SHU record:", error);
            showError(
                `Gagal menyimpan laporan SHU: ${error.response?.data?.message || error.message}`,
            );
        }
    }

    async function deleteSHURecord(id: number) {
        if (!id || id === undefined || id === null) {
            console.error("Invalid ID for deletion:", id);
            showError("Error: ID SHU tidak valid untuk penghapusan");
            return;
        }

        if (
            !confirm(
                `Apakah Anda yakin ingin menghapus laporan SHU dengan ID ${id}?`,
            )
        ) {
            return;
        }

        try {
            const response = await axios.delete(`/shu/${id}`);

            // Refresh data
            await invalidateAll();

            showSuccessNotification("Laporan SHU berhasil dihapus!");
        } catch (error: any) {
            console.error("❌ Error deleting SHU record:", error);
            console.error("❌ Delete endpoint called:", `/shu/${id}`);
            console.error("❌ Error response:", error.response?.data);

            showError(
                `Gagal menghapus laporan SHU: ${error.response?.data?.message || error.message}`,
            );
        }
    }

    // Note: Year-based deletion removed - we should always use the SHU ID
    // If ID is missing from API response, this indicates a backend issue that should be fixed

    async function generatePDF(shu: SHURecord) {
        try {
            const shuId = shu.id;

            // Check if detailed data is missing and try to generate it
            if (
                !shu.shu_report ||
                !shu.shu_report.detail_anggota ||
                shu.shu_report.detail_anggota.length === 0
            ) {
                showSuccessNotification(
                    "Sedang generate detail data untuk PDF...",
                );

                try {
                    await generateDetailedSHUReport(shu);
                    // Wait a moment for the data to be updated
                    await new Promise((resolve) => setTimeout(resolve, 1000));
                    // Use the updated selectedSHU which should now have shu_report
                    if (selectedSHU) {
                        shu = selectedSHU;
                    }
                } catch (error) {
                    console.warn(
                        "⚠️ Could not generate detailed data, creating PDF without member breakdown",
                    );
                }
            }

            // Create HTML content for PDF
            const htmlContent = `
                <!DOCTYPE html>
                <html>
                <head>
                    <meta charset="utf-8">
                    <title>Laporan SHU ${shu.tahun}</title>
                    <style>
                        body {
                            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                            margin: 30px;
                            line-height: 1.6;
                            color: #333;
                        }
                        .header {
                            text-align: center;
                            margin-bottom: 40px;
                            border-bottom: 3px solid #007bff;
                            padding-bottom: 20px;
                        }
                        .header h1 {
                            color: #007bff;
                            margin-bottom: 10px;
                            font-size: 24px;
                        }
                        .header h2 {
                            color: #333;
                            margin-bottom: 5px;
                        }
                        .info-grid {
                            display: grid;
                            grid-template-columns: 1fr 1fr;
                            gap: 20px;
                            margin-bottom: 30px;
                        }
                        .info-item {
                            margin-bottom: 15px;
                            padding: 10px;
                            background: #f8f9fa;
                            border-left: 4px solid #007bff;
                        }
                        .label {
                            font-weight: bold;
                            color: #666;
                            font-size: 14px;
                        }
                        .value {
                            font-size: 18px;
                            font-weight: bold;
                            color: #333;
                        }
                        .section-title {
                            color: #007bff;
                            border-bottom: 2px solid #e9ecef;
                            padding-bottom: 10px;
                            margin-top: 30px;
                            margin-bottom: 20px;
                        }
                        .summary-cards {
                            display: grid;
                            grid-template-columns: repeat(3, 1fr);
                            gap: 15px;
                            margin-bottom: 25px;
                        }
                        .summary-card {
                            padding: 15px;
                            border-radius: 8px;
                            text-align: center;
                            border: 1px solid #dee2e6;
                        }
                        .summary-card.blue {
                            background: #e3f2fd;
                            border-color: #2196f3;
                        }
                        .summary-card.green {
                            background: #e8f5e8;
                            border-color: #4caf50;
                        }
                        .summary-card.purple {
                            background: #f3e5f5;
                            border-color: #9c27b0;
                        }
                        table {
                            width: 100%;
                            border-collapse: collapse;
                            margin-top: 20px;
                            border: 1px solid #dee2e6;
                        }
                        th {
                            padding: 12px 8px;
                            text-align: left;
                            background-color: #007bff;
                            color: white;
                            font-weight: bold;
                            font-size: 13px;
                        }
                        td {
                            padding: 10px 8px;
                            border-bottom: 1px solid #dee2e6;
                            font-size: 12px;
                        }
                        .currency {
                            text-align: right;
                            font-family: 'Courier New', monospace;
                        }
                        .total-row {
                            font-weight: bold;
                            background-color: #f8f9fa;
                            border-top: 2px solid #007bff;
                        }
                        .member-info {
                            line-height: 1.4;
                        }
                        .member-email {
                            font-weight: 600;
                            color: #333;
                        }
                        .member-id {
                            font-size: 11px;
                            color: #666;
                        }
                        .footer {
                            margin-top: 50px;
                            text-align: center;
                            color: #666;
                            font-size: 12px;
                            border-top: 1px solid #dee2e6;
                            padding-top: 20px;
                        }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <h1>LAPORAN SISA HASIL USAHA (SHU)</h1>
                        <h2>TAHUN ${shu.tahun}</h2>
                        <p>Tanggal: ${safeDateFormat(shu)}</p>
                    </div>

                    <div class="info-grid">
                        <div class="info-item">
                            <div class="label">Total SHU Koperasi:</div>
                            <div class="value">${formatCurrency(shu.total_shu)}</div>
                        </div>
                        <div class="info-item">
                            <div class="label">Status:</div>
                            <div class="value">${shu.status === "final" ? "Final" : "Draft"}</div>
                        </div>
                    </div>

                    ${
                        shu.shu_report
                            ? `
                    <h3>Detail Perhitungan</h3>
                    <div class="info-grid">
                        <div class="info-item">
                            <div class="label">Persentase Jasa Modal:</div>
                            <div class="value">${shu.shu_report.persen_jasa_modal}%</div>
                        </div>
                        <div class="info-item">
                            <div class="label">Persentase Jasa Usaha:</div>
                            <div class="value">${shu.shu_report.persen_jasa_usaha}%</div>
                        </div>
                        <div class="info-item">
                            <div class="label">Total Simpanan Semua Anggota:</div>
                            <div class="value">${formatCurrency(shu.shu_report.total_simpanan_all)}</div>
                        </div>
                        <div class="info-item">
                            <div class="label">Total Penjualan Semua Anggota:</div>
                            <div class="value">${formatCurrency(shu.shu_report.total_penjualan_all)}</div>
                        </div>
                    </div>

                    <h3 class="section-title">Pembagian SHU kepada Anggota</h3>

                    <div class="summary-cards">
                        <div class="summary-card blue">
                            <div class="label">Total Anggota</div>
                            <div class="value">${shu.shu_report.detail_anggota.length}</div>
                        </div>
                        <div class="summary-card green">
                            <div class="label">Total SHU Dibagikan</div>
                            <div class="value">${formatCurrency(shu.shu_report.detail_anggota.reduce((sum, member) => sum + member.total_shu_anggota, 0))}</div>
                        </div>
                        <div class="summary-card purple">
                            <div class="label">Rata-rata SHU/Anggota</div>
                            <div class="value">${formatCurrency(shu.shu_report.detail_anggota.reduce((sum, member) => sum + member.total_shu_anggota, 0) / shu.shu_report.detail_anggota.length)}</div>
                        </div>
                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th style="width: 5%;">No</th>
                                <th style="width: 25%;">Anggota</th>
                                <th style="width: 14%;">Total Simpanan</th>
                                <th style="width: 14%;">Total Penjualan</th>
                                <th style="width: 14%;">Jasa Modal</th>
                                <th style="width: 14%;">Jasa Usaha</th>
                                <th style="width: 14%;">Total SHU</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${shu.shu_report.detail_anggota
                                .map(
                                    (member, index) => `
                                <tr>
                                    <td style="text-align: center;">${index + 1}</td>
                                    <td class="member-info">
                                        <div class="member-email">${member.email}</div>
                                        <div class="member-id">ID: ${member.user_id}</div>
                                    </td>
                                    <td class="currency">${formatCurrency(member.total_simpanan)}</td>
                                    <td class="currency">${formatCurrency(member.total_penjualan)}</td>
                                    <td class="currency">${formatCurrency(member.jasa_modal)}</td>
                                    <td class="currency">${formatCurrency(member.jasa_usaha)}</td>
                                    <td class="currency" style="font-weight: bold; background-color: #e8f5e8;">${formatCurrency(member.total_shu_anggota)}</td>
                                </tr>
                            `,
                                )
                                .join("")}
                            <tr class="total-row">
                                <td colspan="2" style="text-align: center; font-weight: bold;">TOTAL KESELURUHAN</td>
                                <td class="currency">${formatCurrency(shu.shu_report.detail_anggota.reduce((sum, member) => sum + member.total_simpanan, 0))}</td>
                                <td class="currency">${formatCurrency(shu.shu_report.detail_anggota.reduce((sum, member) => sum + member.total_penjualan, 0))}</td>
                                <td class="currency">${formatCurrency(shu.shu_report.detail_anggota.reduce((sum, member) => sum + member.jasa_modal, 0))}</td>
                                <td class="currency">${formatCurrency(shu.shu_report.detail_anggota.reduce((sum, member) => sum + member.jasa_usaha, 0))}</td>
                                <td class="currency" style="font-weight: bold; background-color: #d4edda;">${formatCurrency(shu.shu_report.detail_anggota.reduce((sum, member) => sum + member.total_shu_anggota, 0))}</td>
                            </tr>
                        </tbody>
                    </table>
                    `
                            : ""
                    }

                    <div class="footer">
                        <p><strong>Laporan Sisa Hasil Usaha (SHU) Koperasi</strong></p>
                        <p>Laporan ini digenerate secara otomatis oleh sistem</p>
                        <p>Tanggal generate: ${new Date().toLocaleString("id-ID")}</p>
                        <p style="margin-top: 10px; font-style: italic;">* Semua perhitungan mengacu pada data transaksi yang tercatat dalam sistem</p>
                    </div>
                </body>
                </html>
            `;

            // Create and download HTML file (can be opened in browser and printed to PDF)
            const blob = new Blob([htmlContent], { type: "text/html" });
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `SHU_Report_${shu.tahun}.html`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            window.URL.revokeObjectURL(url);

            showSuccessNotification(
                "Laporan SHU berhasil diunduh! Buka file HTML dan print ke PDF di browser.",
            );
        } catch (error: any) {
            console.error("❌ Error generating PDF:", error);
            showError(`Gagal membuat PDF: ${error.message}`);
        }
    }
</script>

<svelte:head>
    <title>SHU Report - Koperasi Backoffice</title>
</svelte:head>

<div class="p-6 animate-fade-in">
    <!-- Page Header -->
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8">
        <div>
            <h1 class="text-2xl font-bold text-slate-900">
                {canManageSHU ? "Kelola Laporan SHU" : "SHU Saya"}
            </h1>
            <p class="text-slate-500 mt-1">
                {canManageSHU
                    ? "Kelola laporan Sisa Hasil Usaha koperasi"
                    : "Lihat riwayat dan generate SHU pribadi Anda"}
            </p>
        </div>

        {#if canManageSHU}
            <div class="flex gap-2">
                <button
                    on:click={openGenerateModal}
                    class="btn btn-secondary"
                >
                    <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z"/></svg>
                    Generate Manual
                </button>
                <button
                    on:click={openAutoGenerateModal}
                    class="btn btn-primary"
                >
                    <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
                    Generate Otomatis
                </button>
            </div>
        {:else}
            <button
                on:click={openUserGenerateModal}
                class="btn btn-primary"
            >
                <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z"/></svg>
                Generate SHU Saya
            </button>
        {/if}
    </div>

    <!-- Summary Stats (teal-tinted) -->
    {#if canManageSHU && shuRecords.length > 0}
        <div class="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
            <div class="card stagger-item" style="background: linear-gradient(135deg, #f0fdfa 0%, #ccfbf1 100%); border: 1px solid #99f6e4;">
                <div class="p-4">
                    <p class="text-sm font-medium text-teal-600">Total Laporan</p>
                    <p class="text-2xl font-bold text-teal-900 mt-1 font-tabular">{shuRecords.length}</p>
                </div>
            </div>
            <div class="card stagger-item" style="background: linear-gradient(135deg, #f0fdfa 0%, #ccfbf1 100%); border: 1px solid #99f6e4;">
                <div class="p-4">
                    <p class="text-sm font-medium text-teal-600">Total SHU Keseluruhan</p>
                    <p class="text-xl font-bold text-teal-900 mt-1 font-tabular">{formatCurrency(shuRecords.reduce((sum, r) => sum + (r.total_shu || 0), 0))}</p>
                </div>
            </div>
            <div class="card stagger-item" style="background: linear-gradient(135deg, #f0fdfa 0%, #ccfbf1 100%); border: 1px solid #99f6e4;">
                <div class="p-4">
                    <p class="text-sm font-medium text-teal-600">Status Final</p>
                    <p class="text-2xl font-bold text-teal-900 mt-1 font-tabular">{shuRecords.filter(r => r.status === 'final').length} <span class="text-sm font-normal text-teal-500">/ {shuRecords.length}</span></p>
                </div>
            </div>
        </div>
    {/if}

    <!-- Main Content -->
    {#if canManageSHU}
        <!-- Admin/Super Admin View: SHU Records as Cards -->
        {#if shuRecords.length === 0}
            <div class="card">
                <div class="empty-state py-12">
                    <svg class="w-16 h-16 mx-auto mb-4 text-slate-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
                    </svg>
                    <p class="text-slate-500 text-lg mb-1">Belum ada laporan SHU</p>
                    <p class="text-slate-400 text-sm mb-6">Mulai dengan membuat laporan SHU pertama Anda</p>
                    <div class="flex gap-2 justify-center">
                        <button
                            on:click={openGenerateModal}
                            class="btn btn-secondary btn-sm"
                        >
                            Generate Manual
                        </button>
                        <button
                            on:click={openAutoGenerateModal}
                            class="btn btn-primary btn-sm"
                        >
                            Generate Otomatis
                        </button>
                    </div>
                </div>
            </div>
        {:else}
            <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
                {#each shuRecords as shu, index}
                    <div class="card card-interactive animate-slide-up stagger-item">
                        <div class="p-5">
                            <!-- Year Header -->
                            <div class="flex items-start justify-between mb-4">
                                <div>
                                    <div class="text-3xl font-bold text-slate-900 font-tabular">{shu.tahun}</div>
                                    <p class="text-xs text-slate-400 mt-0.5">{safeDateFormat(shu)}</p>
                                </div>
                                <span class="badge {shu.status === 'final' ? 'badge-success' : 'badge-warning'}">
                                    {shu.status === "final" ? "Final" : "Draft"}
                                </span>
                            </div>

                            <!-- Total SHU -->
                            <div class="mb-4 p-3 rounded-lg" style="background: #f0fdfa;">
                                <p class="text-xs font-medium text-teal-600 uppercase tracking-wide">Total SHU</p>
                                <p class="text-xl font-bold text-teal-800 font-tabular mt-0.5">
                                    {formatCurrency(shu.total_shu)}
                                </p>
                            </div>

                            <!-- Actions -->
                            <div class="flex gap-2 pt-2 border-t border-slate-100">
                                <button
                                    on:click={() => openDetailModal(shu)}
                                    class="btn btn-ghost btn-sm flex-1"
                                >
                                    <svg class="w-3.5 h-3.5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>
                                    Detail
                                </button>
                                <button
                                    on:click={() => generatePDF(shu)}
                                    class="btn btn-ghost btn-sm flex-1"
                                >
                                    <svg class="w-3.5 h-3.5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                                    PDF
                                </button>
                                <button
                                    on:click={() => {
                                        const shuId = shu.ID || shu.id;
                                        if (shuId) {
                                            deleteSHURecord(shuId);
                                        } else {
                                            console.error(
                                                "❌ SHU record missing ID field:",
                                                shu,
                                            );
                                            showError(
                                                "Error: ID SHU tidak ditemukan. Tidak dapat menghapus record ini.",
                                            );
                                        }
                                    }}
                                    class="btn btn-danger btn-sm"
                                >
                                    <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                                </button>
                            </div>
                        </div>
                    </div>
                {/each}
            </div>
        {/if}
    {:else}
        <!-- Member View: Personal SHU History -->
        <div class="card animate-slide-up">
            <div class="p-5 border-b border-slate-100 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
                <div>
                    <h2 class="text-lg font-semibold text-slate-900">Riwayat SHU Saya</h2>
                    <p class="text-sm text-slate-500 mt-0.5">
                        Lihat riwayat SHU yang pernah Anda terima
                    </p>
                </div>
                <div class="flex gap-2">
                    <button
                        on:click={() => {
                            showUserSaveModal = true;
                        }}
                        class="btn btn-primary btn-sm"
                        disabled={savingUserSHU}
                    >
                        <svg class="w-3.5 h-3.5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4"/></svg>
                        Simpan SHU
                    </button>
                    <button
                        on:click={refreshUserData}
                        class="btn btn-ghost btn-sm"
                    >
                        <svg class="w-3.5 h-3.5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
                        Refresh
                    </button>
                </div>
            </div>

            {#if userShuHistory.length === 0}
                <div class="empty-state py-12 px-6">
                    <svg class="w-16 h-16 mx-auto mb-4 text-slate-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
                    </svg>
                    <p class="text-slate-500 text-lg mb-1">Belum ada riwayat SHU</p>
                    <p class="text-slate-400 text-sm mb-6">Belum ada riwayat SHU tersimpan untuk akun Anda</p>

                    <div class="alert alert-info max-w-lg mx-auto text-left mb-6">
                        <p class="font-semibold mb-2">Cara Mendapatkan SHU:</p>
                        <ul class="space-y-1 text-sm">
                            <li>Klik tombol "Simpan SHU" untuk menyimpan SHU tahunan Anda</li>
                            <li>SHU dihitung berdasarkan kontribusi simpanan dan transaksi Anda</li>
                            <li>Hasil tersimpan akan muncul di riwayat dengan status draft/final</li>
                            <li>Jika tombol tidak berfungsi, hubungi admin</li>
                        </ul>
                    </div>

                    <div class="flex gap-2 justify-center">
                        <button
                            on:click={() => {
                                showUserSaveModal = true;
                            }}
                            class="btn btn-primary"
                        >
                            <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4"/></svg>
                            Simpan SHU Saya
                        </button>
                        <button
                            on:click={openUserGenerateModal}
                            class="btn btn-secondary"
                        >
                            Generate SHU (Legacy)
                        </button>
                    </div>
                </div>
            {:else}
                <div class="table-container">
                    <table>
                        <thead>
                            <tr>
                                <th>Periode</th>
                                <th>Jasa Modal</th>
                                <th>Jasa Usaha</th>
                                <th>Total SHU</th>
                                <th>Status</th>
                                <th>Tanggal</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            {#each userShuHistory as userShu, index}
                                <tr>
                                    <td class="font-semibold text-slate-900 font-tabular">
                                        {userShu.shu?.tahun ||
                                            userShu.periode ||
                                            userShu.tahun ||
                                            userShu.year ||
                                            "N/A"}
                                    </td>
                                    <td class="font-tabular">
                                        {formatCurrency(
                                            userShu.jumlah_modal ||
                                                userShu.jasa_modal ||
                                                userShu.JasaModal ||
                                                0,
                                        )}
                                    </td>
                                    <td class="font-tabular">
                                        {formatCurrency(
                                            userShu.jumlah_usaha ||
                                                userShu.jasa_usaha ||
                                                userShu.JasaUsaha ||
                                                0,
                                        )}
                                    </td>
                                    <td class="font-semibold font-tabular text-teal-700">
                                        {formatCurrency(
                                            userShu.shu_diterima ||
                                                userShu.total_shu_anggota ||
                                                userShu.TotalSHUAnggota ||
                                                userShu.total_shu ||
                                                userShu.TotalSHU ||
                                                0,
                                        )}
                                    </td>
                                    <td>
                                        <span class="badge {userShu.shu?.status === 'final' ? 'badge-success' : 'badge-warning'}">
                                            {userShu.shu?.status === "final"
                                                ? "Final"
                                                : "Draft"}
                                        </span>
                                    </td>
                                    <td class="text-slate-500 text-sm">
                                        {formatDate(
                                            userShu.created_at ||
                                                userShu.CreatedAt ||
                                                userShu.tanggal_generate ||
                                                userShu.TanggalGenerate ||
                                                new Date().toISOString(),
                                        )}
                                    </td>
                                    <td>
                                        {#if userShu.shu?.tahun}
                                            <button
                                                on:click={() => {
                                                    userSaveTahun =
                                                        userShu.shu.tahun;
                                                    showUserSaveModal = true;
                                                }}
                                                class="btn btn-ghost btn-sm"
                                                disabled={savingUserSHU}
                                            >
                                                <svg class="w-3.5 h-3.5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
                                                Simpan Ulang
                                            </button>
                                        {/if}
                                    </td>
                                </tr>
                            {/each}
                        </tbody>
                    </table>
                </div>
            {/if}
        </div>
    {/if}
</div>

<!-- Generate SHU Drawer -->
{#if showGenerateModal}
    <div class="drawer-overlay" on:click={closeModals} on:keydown={(e) => e.key === 'Escape' && closeModals()}>
        <div class="drawer-panel animate-slide-in-right" on:click|stopPropagation on:keydown|stopPropagation>
            <div class="drawer-header">
                <h3 class="text-lg font-semibold text-slate-900">Generate Laporan SHU</h3>
                <button on:click={closeModals} class="btn btn-ghost btn-sm" aria-label="Tutup">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
                </button>
            </div>

            <div class="drawer-body">
                <form on:submit|preventDefault={generateSHUReport} class="space-y-5">
                    <div>
                        <label for="tahun" class="input-label">Tahun</label>
                        <input
                            type="number"
                            id="tahun"
                            bind:value={generateForm.tahun}
                            min="2020"
                            max="2030"
                            class="input"
                            required
                        />
                    </div>

                    <div>
                        <label for="total_shu_koperasi" class="input-label">Total SHU Koperasi</label>
                        <input
                            type="number"
                            id="total_shu_koperasi"
                            bind:value={generateForm.total_shu_koperasi}
                            min="0"
                            step="1000"
                            class="input"
                            required
                        />
                    </div>

                    <div class="flex gap-3 pt-2">
                        <button type="button" on:click={closeModals} class="btn btn-secondary flex-1">
                            Batal
                        </button>
                        <button type="submit" class="btn btn-primary flex-1">
                            <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
                            Generate
                        </button>
                    </div>
                </form>

                <!-- Generated Report Display -->
                {#if generatedReport}
                    <div class="mt-6 pt-6 border-t border-slate-200">
                        <h4 class="text-base font-semibold text-slate-900 mb-4">Hasil Generate SHU</h4>

                        <div class="grid grid-cols-2 gap-3 mb-4">
                            <div class="p-3 rounded-lg bg-slate-50">
                                <p class="text-xs text-slate-500">Tahun</p>
                                <p class="font-semibold text-slate-900 font-tabular">{generatedReport.tahun}</p>
                            </div>
                            <div class="p-3 rounded-lg" style="background: #f0fdfa;">
                                <p class="text-xs text-teal-600">Total SHU Koperasi</p>
                                <p class="font-semibold text-teal-800 font-tabular">
                                    {formatCurrency(generatedReport.total_shu_koperasi)}
                                </p>
                            </div>
                            <div class="p-3 rounded-lg bg-slate-50">
                                <p class="text-xs text-slate-500">Persen Jasa Modal</p>
                                <p class="font-semibold text-slate-900 font-tabular">{generatedReport.persen_jasa_modal}%</p>
                            </div>
                            <div class="p-3 rounded-lg bg-slate-50">
                                <p class="text-xs text-slate-500">Persen Jasa Usaha</p>
                                <p class="font-semibold text-slate-900 font-tabular">{generatedReport.persen_jasa_usaha}%</p>
                            </div>
                            <div class="p-3 rounded-lg bg-slate-50">
                                <p class="text-xs text-slate-500">Total Simpanan</p>
                                <p class="font-semibold text-slate-900 font-tabular">
                                    {formatCurrency(generatedReport.total_simpanan_all)}
                                </p>
                            </div>
                            <div class="p-3 rounded-lg bg-slate-50">
                                <p class="text-xs text-slate-500">Total Penjualan</p>
                                <p class="font-semibold text-slate-900 font-tabular">
                                    {formatCurrency(generatedReport.total_penjualan_all)}
                                </p>
                            </div>
                        </div>

                        <div class="mb-4">
                            <h5 class="text-sm font-semibold text-slate-700 mb-2">
                                Detail Anggota ({generatedReport.detail_anggota.length} orang)
                            </h5>
                            <div class="table-container max-h-48 overflow-y-auto">
                                <table>
                                    <thead>
                                        <tr>
                                            <th>Email</th>
                                            <th>Simpanan</th>
                                            <th>Penjualan</th>
                                            <th>Total SHU</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {#each generatedReport.detail_anggota as member}
                                            <tr>
                                                <td class="text-sm">{member.email}</td>
                                                <td class="font-tabular text-sm">{formatCurrency(member.total_simpanan)}</td>
                                                <td class="font-tabular text-sm">{formatCurrency(member.total_penjualan)}</td>
                                                <td class="font-semibold font-tabular text-sm">{formatCurrency(member.total_shu_anggota)}</td>
                                            </tr>
                                        {/each}
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <form on:submit|preventDefault={saveSHUReport} class="space-y-4">
                            <div>
                                <label for="status" class="input-label">Status</label>
                                <select
                                    id="status"
                                    bind:value={saveForm.status}
                                    class="input"
                                >
                                    <option value="draft">Draft</option>
                                    <option value="final">Final</option>
                                </select>
                            </div>

                            <div class="flex gap-3">
                                <button type="button" on:click={closeModals} class="btn btn-secondary flex-1">
                                    Batal
                                </button>
                                <button type="submit" class="btn btn-primary flex-1">
                                    <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4"/></svg>
                                    Simpan Laporan
                                </button>
                            </div>
                        </form>
                    </div>
                {/if}
            </div>
        </div>
    </div>
{/if}

<!-- Automated Generate SHU Drawer -->
{#if showAutoGenerateModal}
    <div class="drawer-overlay" on:click={closeModals} on:keydown={(e) => e.key === 'Escape' && closeModals()}>
        <div class="drawer-panel animate-slide-in-right" on:click|stopPropagation on:keydown|stopPropagation>
            <div class="drawer-header">
                <h3 class="text-lg font-semibold text-slate-900">Generate SHU Otomatis</h3>
                <button on:click={closeModals} class="btn btn-ghost btn-sm" aria-label="Tutup">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
                </button>
            </div>

            <div class="drawer-body">
                <p class="text-sm text-slate-500 mb-5">Masukkan data keuangan untuk perhitungan SHU otomatis</p>

                <form on:submit|preventDefault={generateAutoSHUReport} class="space-y-4">
                    <div class="grid grid-cols-2 gap-4">
                        <div class="col-span-2 sm:col-span-1">
                            <label for="tahun_auto" class="input-label">Tahun</label>
                            <input
                                type="number"
                                id="tahun_auto"
                                bind:value={autoGenerateForm.tahun}
                                min="2020"
                                max="2030"
                                class="input"
                                required
                            />
                        </div>

                        <div class="col-span-2 sm:col-span-1">
                            <label for="beban_operasional" class="input-label">Beban Operasional</label>
                            <input
                                type="number"
                                id="beban_operasional"
                                bind:value={autoGenerateForm.beban_operasional}
                                min="0"
                                step="1000"
                                class="input"
                                required
                            />
                        </div>

                        <div class="col-span-2 sm:col-span-1">
                            <label for="beban_non_operasional" class="input-label">Beban Non-Operasional</label>
                            <input
                                type="number"
                                id="beban_non_operasional"
                                bind:value={autoGenerateForm.beban_non_operasional}
                                min="0"
                                step="1000"
                                class="input"
                                required
                            />
                        </div>

                        <div class="col-span-2 sm:col-span-1">
                            <label for="beban_pajak" class="input-label">Beban Pajak</label>
                            <input
                                type="number"
                                id="beban_pajak"
                                bind:value={autoGenerateForm.beban_pajak}
                                min="0"
                                step="1000"
                                class="input"
                                required
                            />
                        </div>
                    </div>

                    <!-- Information Note -->
                    <div class="alert alert-info">
                        <p class="font-semibold text-sm mb-1.5">Informasi Perhitungan</p>
                        <div class="text-sm space-y-1">
                            <p>Pendapatan operasional dan non-operasional dihitung otomatis oleh sistem.</p>
                            <p>Formula: SHU = (Pendapatan Op + Non-Op) - (Beban Op + Non-Op + Pajak)</p>
                            <p>Total beban: <span class="font-semibold font-tabular">{formatCurrency(autoGenerateForm.beban_operasional + autoGenerateForm.beban_non_operasional + autoGenerateForm.beban_pajak)}</span></p>
                        </div>
                    </div>

                    <div class="flex gap-3 pt-2">
                        <button type="button" on:click={closeModals} class="btn btn-secondary flex-1">
                            Batal
                        </button>
                        <button type="submit" class="btn btn-primary flex-1">
                            <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
                            Generate Otomatis
                        </button>
                    </div>
                </form>

                <!-- Auto Generated Report Display -->
                {#if autoGeneratedReport}
                    <div class="mt-6 pt-6 border-t border-slate-200">
                        <h4 class="text-base font-semibold text-slate-900 mb-4">Hasil Generate SHU Otomatis</h4>

                        <div class="grid grid-cols-2 gap-3 mb-4">
                            <div class="p-3 rounded-lg bg-slate-50">
                                <p class="text-xs text-slate-500">Tahun</p>
                                <p class="font-semibold text-slate-900 font-tabular">{autoGeneratedReport.tahun}</p>
                            </div>
                            <div class="p-3 rounded-lg" style="background: #f0fdfa;">
                                <p class="text-xs text-teal-600">Total SHU Koperasi</p>
                                <p class="font-semibold text-teal-800 font-tabular">
                                    {formatCurrency(autoGeneratedReport.total_shu_koperasi)}
                                </p>
                            </div>
                            <div class="p-3 rounded-lg bg-slate-50">
                                <p class="text-xs text-slate-500">Pendapatan Operasional</p>
                                <p class="font-semibold text-slate-900 font-tabular">
                                    {formatCurrency(autoGeneratedReport.pendapatan_operasional)}
                                </p>
                            </div>
                            <div class="p-3 rounded-lg bg-slate-50">
                                <p class="text-xs text-slate-500">Pendapatan Non-Op</p>
                                <p class="font-semibold text-slate-900 font-tabular">
                                    {formatCurrency(autoGeneratedReport.pendapatan_non_operasional)}
                                </p>
                            </div>
                            <div class="p-3 rounded-lg bg-slate-50">
                                <p class="text-xs text-slate-500">Total Simpanan Semua</p>
                                <p class="font-semibold text-slate-900 font-tabular">
                                    {formatCurrency(autoGeneratedReport.total_simpanan_all)}
                                </p>
                            </div>
                            <div class="p-3 rounded-lg bg-slate-50">
                                <p class="text-xs text-slate-500">Total Penjualan Semua</p>
                                <p class="font-semibold text-slate-900 font-tabular">
                                    {formatCurrency(autoGeneratedReport.total_penjualan_all)}
                                </p>
                            </div>
                        </div>

                        <!-- Financial Breakdown -->
                        <div class="mb-4 p-4 rounded-lg bg-slate-50 space-y-2 text-sm">
                            <p class="font-semibold text-slate-700 mb-2">Detail Keuangan</p>
                            <div class="flex justify-between">
                                <span class="text-teal-700">Pendapatan Operasional</span>
                                <span class="font-medium font-tabular">{formatCurrency(autoGeneratedReport.pendapatan_operasional)}</span>
                            </div>
                            <div class="flex justify-between">
                                <span class="text-teal-700">Pendapatan Non-Operasional</span>
                                <span class="font-medium font-tabular">{formatCurrency(autoGeneratedReport.pendapatan_non_operasional)}</span>
                            </div>
                            <div class="flex justify-between">
                                <span class="text-red-600">Beban Operasional</span>
                                <span class="font-medium font-tabular">({formatCurrency(autoGeneratedReport.beban_operasional)})</span>
                            </div>
                            <div class="flex justify-between">
                                <span class="text-red-600">Beban Non-Operasional</span>
                                <span class="font-medium font-tabular">({formatCurrency(autoGeneratedReport.beban_non_operasional)})</span>
                            </div>
                            <div class="flex justify-between">
                                <span class="text-red-600">Beban Pajak</span>
                                <span class="font-medium font-tabular">({formatCurrency(autoGeneratedReport.beban_pajak)})</span>
                            </div>
                            <div class="border-t border-slate-200 pt-2 mt-2 flex justify-between text-base font-bold">
                                <span class="text-slate-900">SHU Total</span>
                                <span class="text-teal-700 font-tabular">{formatCurrency(autoGeneratedReport.total_shu_koperasi)}</span>
                            </div>
                        </div>

                        <!-- Member Detail Table -->
                        <div class="mb-4">
                            <h5 class="text-sm font-semibold text-slate-700 mb-2">
                                Detail Pembagian SHU ({autoGeneratedReport.detail_anggota.length} anggota)
                            </h5>
                            <div class="table-container max-h-48 overflow-y-auto">
                                <table>
                                    <thead>
                                        <tr>
                                            <th>Email</th>
                                            <th>Simpanan</th>
                                            <th>Penjualan</th>
                                            <th>Jasa Modal</th>
                                            <th>Jasa Usaha</th>
                                            <th>Total SHU</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {#each autoGeneratedReport.detail_anggota as member}
                                            <tr>
                                                <td class="text-sm">{member.email}</td>
                                                <td class="font-tabular text-sm">{formatCurrency(member.total_simpanan)}</td>
                                                <td class="font-tabular text-sm">{formatCurrency(member.total_penjualan)}</td>
                                                <td class="font-tabular text-sm">{formatCurrency(member.jasa_modal)}</td>
                                                <td class="font-tabular text-sm">{formatCurrency(member.jasa_usaha)}</td>
                                                <td class="font-semibold font-tabular text-sm">{formatCurrency(member.total_shu_anggota)}</td>
                                            </tr>
                                        {/each}
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <div class="flex gap-3">
                            <button type="button" on:click={closeModals} class="btn btn-secondary flex-1">
                                Tutup
                            </button>
                            <button type="button" on:click={saveAutoSHUReport} class="btn btn-primary flex-1">
                                <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4"/></svg>
                                Simpan ke Daftar SHU
                            </button>
                        </div>
                    </div>
                {/if}
            </div>
        </div>
    </div>
{/if}

<!-- User Generate SHU Modal -->
{#if showUserGenerateModal}
    <div class="modal-overlay animate-fade-in" on:click={closeModals} on:keydown={(e) => e.key === 'Escape' && closeModals()}>
        <div class="modal-panel animate-slide-up" on:click|stopPropagation on:keydown|stopPropagation style="max-width: 28rem;">
            <div class="modal-header">
                <div>
                    <h3 class="text-lg font-semibold text-slate-900">Generate SHU Pribadi</h3>
                    <p class="text-sm text-slate-500 mt-0.5">
                        Generate laporan SHU berdasarkan aktivitas simpan-pinjam Anda
                    </p>
                </div>
            </div>

            <div class="modal-body">
                <div class="alert alert-info mb-0">
                    <p class="font-semibold text-sm mb-1.5">Informasi</p>
                    <ul class="text-sm space-y-1">
                        <li>SHU dihitung berdasarkan simpanan dan transaksi Anda</li>
                        <li>Perhitungan menggunakan formula yang telah ditetapkan koperasi</li>
                        <li>Hasil akan ditampilkan di riwayat SHU Anda</li>
                    </ul>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" on:click={closeModals} class="btn btn-secondary">
                    Batal
                </button>
                <button type="button" on:click={generateUserSHU} class="btn btn-primary">
                    <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
                    Generate SHU Saya
                </button>
            </div>
        </div>
    </div>
{/if}

<!-- User Save SHU Modal -->
{#if showUserSaveModal}
    <div class="modal-overlay animate-fade-in" on:click={closeModals} on:keydown={(e) => e.key === 'Escape' && closeModals()}>
        <div class="modal-panel animate-slide-up" on:click|stopPropagation on:keydown|stopPropagation style="max-width: 28rem;">
            <div class="modal-header">
                <div>
                    <h3 class="text-lg font-semibold text-slate-900">Simpan SHU Pribadi</h3>
                    <p class="text-sm text-slate-500 mt-0.5">
                        Simpan laporan SHU Anda ke dalam database
                    </p>
                </div>
            </div>

            <div class="modal-body space-y-4">
                <div>
                    <label for="userSaveTahun" class="input-label">Tahun SHU</label>
                    <input
                        id="userSaveTahun"
                        type="number"
                        bind:value={userSaveTahun}
                        min="2020"
                        max="2030"
                        class="input"
                        placeholder="Masukkan tahun (contoh: 2024)"
                    />
                </div>

                <div class="alert alert-info">
                    <p class="font-semibold text-sm mb-1.5">Informasi</p>
                    <ul class="text-sm space-y-1">
                        <li>SHU akan dihitung dan disimpan berdasarkan data tahun yang dipilih</li>
                        <li>Pastikan Anda sudah memiliki aktivitas di tahun tersebut</li>
                        <li>Data yang disimpan akan muncul di riwayat SHU Anda</li>
                    </ul>
                </div>
            </div>

            <div class="modal-footer">
                <button
                    type="button"
                    on:click={closeModals}
                    class="btn btn-secondary"
                    disabled={savingUserSHU}
                >
                    Batal
                </button>
                <button
                    type="button"
                    on:click={async () => {
                        savingUserSHU = true;
                        await saveUserSHU(userSaveTahun);
                        savingUserSHU = false;
                        closeModals();
                    }}
                    class="btn btn-primary"
                    disabled={savingUserSHU || !userSaveTahun}
                >
                    {#if savingUserSHU}
                        <svg class="w-4 h-4 mr-1.5 animate-spin" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>
                        Menyimpan...
                    {:else}
                        <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4"/></svg>
                        Simpan SHU
                    {/if}
                </button>
            </div>
        </div>
    </div>
{/if}

<!-- Detail SHU Drawer -->
{#if showDetailModal && selectedSHU}
    <div class="drawer-overlay" on:click={closeModals} on:keydown={(e) => e.key === 'Escape' && closeModals()}>
        <div class="drawer-panel animate-slide-in-right" style="max-width: 56rem;" on:click|stopPropagation on:keydown|stopPropagation>
            <div class="drawer-header">
                <div>
                    <h3 class="text-lg font-semibold text-slate-900">Detail Laporan SHU</h3>
                    <p class="text-sm text-slate-500">Tahun {selectedSHU.tahun}</p>
                </div>
                <button on:click={closeModals} class="btn btn-ghost btn-sm" aria-label="Tutup">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
                </button>
            </div>

            <div class="drawer-body">
                <!-- Top info cards -->
                <div class="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
                    <div class="p-3 rounded-lg bg-slate-50">
                        <p class="text-xs text-slate-500">Tahun</p>
                        <p class="text-xl font-bold text-slate-900 font-tabular">{selectedSHU.tahun}</p>
                    </div>
                    <div class="p-3 rounded-lg" style="background: #f0fdfa;">
                        <p class="text-xs text-teal-600">Total SHU</p>
                        <p class="text-lg font-bold text-teal-800 font-tabular">
                            {formatCurrency(selectedSHU.total_shu)}
                        </p>
                    </div>
                    <div class="p-3 rounded-lg bg-slate-50">
                        <p class="text-xs text-slate-500">Status</p>
                        <span class="badge mt-1 {selectedSHU.status === 'final' ? 'badge-success' : 'badge-warning'}">
                            {selectedSHU.status === "final" ? "Final" : "Draft"}
                        </span>
                    </div>
                    <div class="p-3 rounded-lg bg-slate-50">
                        <p class="text-xs text-slate-500">Tanggal Dibuat</p>
                        <p class="font-semibold text-slate-900 text-sm mt-0.5">
                            {safeDateFormat(selectedSHU)}
                        </p>
                    </div>
                </div>

                {#if selectedSHU.shu_report}
                    <!-- Calculation Details -->
                    <div class="border-t border-slate-200 pt-5 mb-5">
                        <h4 class="text-sm font-semibold text-slate-700 uppercase tracking-wide mb-3">Detail Perhitungan</h4>

                        <div class="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
                            <div class="p-3 rounded-lg bg-slate-50">
                                <p class="text-xs text-slate-500">Persen Jasa Modal</p>
                                <p class="font-semibold text-slate-900 font-tabular">{selectedSHU.shu_report.persen_jasa_modal}%</p>
                            </div>
                            <div class="p-3 rounded-lg bg-slate-50">
                                <p class="text-xs text-slate-500">Persen Jasa Usaha</p>
                                <p class="font-semibold text-slate-900 font-tabular">{selectedSHU.shu_report.persen_jasa_usaha}%</p>
                            </div>
                            <div class="p-3 rounded-lg bg-slate-50">
                                <p class="text-xs text-slate-500">Total Simpanan Semua</p>
                                <p class="font-semibold text-slate-900 font-tabular text-sm">
                                    {formatCurrency(selectedSHU.shu_report.total_simpanan_all)}
                                </p>
                            </div>
                            <div class="p-3 rounded-lg bg-slate-50">
                                <p class="text-xs text-slate-500">Total Penjualan Semua</p>
                                <p class="font-semibold text-slate-900 font-tabular text-sm">
                                    {formatCurrency(selectedSHU.shu_report.total_penjualan_all)}
                                </p>
                            </div>
                        </div>

                        <h4 class="text-sm font-semibold text-slate-700 uppercase tracking-wide mb-3">
                            Pembagian SHU kepada Anggota
                            <span class="text-xs font-normal text-slate-400 normal-case ml-1">
                                ({selectedSHU.shu_report.detail_anggota.length} anggota)
                            </span>
                        </h4>

                        <!-- Summary Cards (teal-tinted) -->
                        <div class="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-5">
                            <div class="card stagger-item" style="background: linear-gradient(135deg, #f0fdfa 0%, #ccfbf1 100%); border: 1px solid #99f6e4;">
                                <div class="p-3 text-center">
                                    <p class="text-xs font-medium text-teal-600">Total Anggota</p>
                                    <p class="text-2xl font-bold text-teal-900 font-tabular">
                                        {selectedSHU.shu_report.detail_anggota.length}
                                    </p>
                                </div>
                            </div>
                            <div class="card stagger-item" style="background: linear-gradient(135deg, #f0fdfa 0%, #ccfbf1 100%); border: 1px solid #99f6e4;">
                                <div class="p-3 text-center">
                                    <p class="text-xs font-medium text-teal-600">Total SHU Dibagikan</p>
                                    <p class="text-lg font-bold text-teal-900 font-tabular">
                                        {formatCurrency(
                                            selectedSHU.shu_report.detail_anggota.reduce(
                                                (sum, member) =>
                                                    sum + member.total_shu_anggota,
                                                0,
                                            ),
                                        )}
                                    </p>
                                </div>
                            </div>
                            <div class="card stagger-item" style="background: linear-gradient(135deg, #f0fdfa 0%, #ccfbf1 100%); border: 1px solid #99f6e4;">
                                <div class="p-3 text-center">
                                    <p class="text-xs font-medium text-teal-600">Rata-rata SHU/Anggota</p>
                                    <p class="text-lg font-bold text-teal-900 font-tabular">
                                        {formatCurrency(
                                            selectedSHU.shu_report.detail_anggota.reduce(
                                                (sum, member) =>
                                                    sum + member.total_shu_anggota,
                                                0,
                                            ) /
                                                selectedSHU.shu_report
                                                    .detail_anggota.length,
                                        )}
                                    </p>
                                </div>
                            </div>
                        </div>

                        <!-- Member Detail Table -->
                        <div class="table-container">
                            <table>
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Anggota</th>
                                        <th class="text-right">Simpanan</th>
                                        <th class="text-right">Penjualan</th>
                                        <th class="text-right">Jasa Modal</th>
                                        <th class="text-right">Jasa Usaha</th>
                                        <th class="text-right" style="background: #f0fdfa;">Total SHU</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {#each selectedSHU.shu_report.detail_anggota as member, index}
                                        <tr>
                                            <td class="text-slate-500 font-tabular">{index + 1}</td>
                                            <td>
                                                <div>
                                                    <p class="font-medium text-slate-900 text-sm">{member.email}</p>
                                                    <p class="text-xs text-slate-400">ID: {member.user_id}</p>
                                                </div>
                                            </td>
                                            <td class="text-right font-tabular text-sm">{formatCurrency(member.total_simpanan)}</td>
                                            <td class="text-right font-tabular text-sm">{formatCurrency(member.total_penjualan)}</td>
                                            <td class="text-right font-tabular text-sm text-teal-600">{formatCurrency(member.jasa_modal)}</td>
                                            <td class="text-right font-tabular text-sm text-teal-600">{formatCurrency(member.jasa_usaha)}</td>
                                            <td class="text-right font-tabular text-sm font-bold text-teal-700" style="background: #f0fdfa;">
                                                {formatCurrency(member.total_shu_anggota)}
                                            </td>
                                        </tr>
                                    {/each}
                                    <!-- Total Row -->
                                    <tr style="background: #f0fdfa; font-weight: 600;">
                                        <td colspan="2" class="font-semibold text-slate-900">TOTAL KESELURUHAN</td>
                                        <td class="text-right font-tabular text-sm">
                                            {formatCurrency(
                                                selectedSHU.shu_report.detail_anggota.reduce(
                                                    (sum, member) =>
                                                        sum +
                                                        member.total_simpanan,
                                                    0,
                                                ),
                                            )}
                                        </td>
                                        <td class="text-right font-tabular text-sm">
                                            {formatCurrency(
                                                selectedSHU.shu_report.detail_anggota.reduce(
                                                    (sum, member) =>
                                                        sum +
                                                        member.total_penjualan,
                                                    0,
                                                ),
                                            )}
                                        </td>
                                        <td class="text-right font-tabular text-sm text-teal-700">
                                            {formatCurrency(
                                                selectedSHU.shu_report.detail_anggota.reduce(
                                                    (sum, member) =>
                                                        sum + member.jasa_modal,
                                                    0,
                                                ),
                                            )}
                                        </td>
                                        <td class="text-right font-tabular text-sm text-teal-700">
                                            {formatCurrency(
                                                selectedSHU.shu_report.detail_anggota.reduce(
                                                    (sum, member) =>
                                                        sum + member.jasa_usaha,
                                                    0,
                                                ),
                                            )}
                                        </td>
                                        <td class="text-right font-tabular text-sm font-bold text-teal-800" style="background: #ccfbf1;">
                                            {formatCurrency(
                                                selectedSHU.shu_report.detail_anggota.reduce(
                                                    (sum, member) =>
                                                        sum +
                                                        member.total_shu_anggota,
                                                    0,
                                                ),
                                            )}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                {:else}
                    <div class="border-t border-slate-200 pt-5">
                        <div class="alert alert-warning">
                            <h4 class="font-semibold mb-2">Data Detail Belum Tersedia</h4>
                            <p class="text-sm mb-3">
                                Laporan SHU ini belum memiliki detail pembagian kepada anggota.
                            </p>
                            <p class="text-sm mb-4">
                                Klik tombol "Regenerate Detail" untuk mendapatkan detail lengkap pembagian.
                            </p>

                            <div class="flex gap-2 mb-3">
                                <button
                                    on:click={() => fetchDetailedSHUData(selectedSHU)}
                                    class="btn btn-primary btn-sm"
                                >
                                    <svg class="w-3.5 h-3.5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
                                    Regenerate Detail
                                </button>
                                <button
                                    on:click={() => generateDetailedSHUReport(selectedSHU)}
                                    class="btn btn-secondary btn-sm"
                                >
                                    <svg class="w-3.5 h-3.5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                                    Generate Report
                                </button>
                            </div>

                            <div class="text-xs text-slate-500 p-2 bg-slate-50 rounded">
                                <p><strong>Tersedia:</strong>
                                {Object.keys(selectedSHU)
                                    .filter(
                                        (key) => !["shu_report"].includes(key),
                                    )
                                    .join(", ")}</p>
                                <p><strong>Total SHU:</strong> <span class="font-tabular">{formatCurrency(selectedSHU.total_shu || 0)}</span></p>
                                <p><strong>ID:</strong> <span class="font-tabular">{selectedSHU.ID || selectedSHU.id || "N/A"}</span></p>
                            </div>
                        </div>
                    </div>
                {/if}
            </div>

            <div class="drawer-footer">
                <button
                    on:click={() => generatePDF(selectedSHU)}
                    class="btn btn-primary"
                >
                    <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                    Download PDF
                </button>
                <button on:click={closeModals} class="btn btn-secondary">
                    Tutup
                </button>
            </div>
        </div>
    </div>
{/if}
